### ISSUE TITLE
count_token_messages_failed unsupported input type (request id: 202403221435429848190923cziwZCQ)

### ISSUE THREAD

**Issue by hansn123** [labring/FastGPT#1050]
私有部署版本
OPENAI_BASE_URL配置的是openai的地址
**问题描述**
聊天对话，输入任何提问语句，页面都会报错：count_token_messages_failed unsupported input type (request id: 202403221435429848190923cziwZCQ)

后台错误如下：
[ERROR] 2024-03-22 06:35:43 sse error: count_token_messages_failed unsupported input type (request id: 202403221435429848190923cziwZCQ) 
Embedding Error eY [Error]: 500 unsupported input type (request id: 20240322143543396694598QKKNVNCL)
    at eL.generate (/app/projects/app/.next/server/chunks/53204.js:21:70210)
    at ax.makeStatusError (/app/projects/app/.next/server/chunks/53204.js:21:81454)
    at ax.makeRequest (/app/projects/app/.next/server/chunks/53204.js:21:82188)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async W (/app/projects/app/.next/server/chunks/82729.js:31:1242)
    at async k (/app/projects/app/.next/server/chunks/5182.js:54:18331)
    at async Promise.all (index 0)
    at async /app/projects/app/.next/server/chunks/5182.js:55:403
    at async Promise.all (index 1) {
  status: 500,
  headers: {
    connection: 'keep-alive',
    'content-length': '163',
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 22 Mar 2024 06:35:43 GMT',
    server: 'cdn',
    'strict-transport-security': 'max-age=31536000',
    'x-oneapi-request-id': '20240322143543396694598QKKNVNCL'
  },
  error: {
    message: 'unsupported input type (request id: 20240322143543396694598QKKNVNCL)',
    type: 'new_api_error',
    param: '',
    code: 'count_token_messages_failed'
  },
  code: 'count_token_messages_failed',
  param: '',
  type: 'new_api_error'
}
**相关截图**

**Comment by c121914yu** [comment]
oneapi太老了吧，不支持新的输入格式。
