### ISSUE TITLE
升级到4.7后调用luanshaotong/reranker:v0.1报错TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Andy1018** [labring/FastGPT#1094]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述**
INFO:     172.17.0.1:30770 - "POST /api/v1/rerank HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/conda/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/opt/conda/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/workspace/app.py", line 97, in handle_post_request
    qa_docs_with_rerank = chat.fit_query_answer_rerank(docs)
  File "/workspace/app.py", line 75, in fit_query_answer_rerank
    if query_docs is None or len(query_docs.inputs) == 0:
TypeError: object of type 'NoneType' has no len()

**复现步骤**

**预期结果**

**相关截图**

**Comment by Andy1018** [comment]
reranker需要切换到v0.2

**Comment by Novalife** [comment]
Unable to find image 'registry.cn-hangzhou.aliyuncs.com/fastgpt/bge-rerank-base:v0.2' locally
docker: Error response from daemon: manifest for registry.cn-hangzhou.aliyuncs.com/fastgpt/bge-rerank-base:v0.2 not found: manifest unknown: manifest unknown.

找不到v0.2的镜像呢

**Comment by MusicOfWind** [comment]
我的rerank是bge-rerank-base:v0.1，fastgpt版本是v4.6.7，调用重排时也是报错object of type 'NoneType' has no len()

**Comment by MusicOfWind** [comment]
> reranker需要切换到v0.2

大哥求助，我的 fastgpt 版本是 V4.6.7，想问问你当时用的是什么 rerank 镜像版本
