### ISSUE TITLE
高级编排使用“文本加工”就报错

### ISSUE THREAD

**Issue by xkkjiayou** [labring/FastGPT#1167]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述**
高级编排使用“文本加工”就报错，
![image](https://github.com/labring/FastGPT/assets/38376865/f1e6f31e-5716-4746-8220-9114b228f7d4)

```[ERROR] 2024-04-09 19:45:47 Http request error
{
  message: 'Request failed with status code 504',
  stack: 'AxiosError: Request failed with status code 500\n' +
    '    at settle (file:///C:/FastGPT-4.7/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/core/settle.js:19:12)\n' +
    '    at IncomingMessage.handleStreamEnd (file:///C:/%E4%BF%9D%E7%A0%94/FastGPT-4.7/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/adapters/http.js:589:11)\n' +
    '    at IncomingMessage.emit (node:events:526:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1589:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n' +
    '    at Axios.request (file:///C:/FastGPT-4.7/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/core/Axios.js:45:41)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async m (C:\\\FastGPT-4.7\\projects\\app\\.next\\server\\chunks\\94900.js:131:4023)\n' +
    '    at async Object.y [as httpRequest468] (C:\\保研\\FastGPT-4.7\\projects\\app\\.next\\server\\chunks\\94900.js:131:3185)\n' +
    '    at async N (C:\\FastGPT-4.7\\projects\\app\\.next\\server\\chunks\\94900.js:130:2805)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async S (C:\FastGPT-4.7\\projects\\app\\.next\\server\\chunks\\94900.js:130:4134)\n' +
    '    at async h (C:\\FastGPT-4.7\\projects\\app\\.next\\server\\pages\\api\\core\\chat\\chatTest.js:1:2771)',
  config: {
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.6.8',
      'Content-Length': '60',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    data: '{"university":"中科大","messages":[],"question":"你好"}'
  },
  response: { status: 504, statusText: 'Gateway Time-out' }
}
```
**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
我用docker部署没遇到类似的问题，你这个路径看上去不是docker部署的？你是源码部署吗？

**Comment by c121914yu** [comment]
看着是源码部署，也没遇到过。。看着是没法请求网络（文本加工会内部自身请求）
