### ISSUE TITLE
创建知识库报错relation "modeldata" does not exist

### ISSUE THREAD

**Issue by ChafLee** [labring/FastGPT#117]
已经执行了init.sql，但还是报错

error: relation "modeldata" does not exist
    at D:\IdeaProjects\FastGPT-main\client\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(api)/./src/pages/api/plugins/kb/list.ts:36:28)
    at async Promise.all (index 2)
    at async handler (webpack-internal:///(api)/./src/pages/api/plugins/kb/list.ts:29:22)
    at async Object.apiResolver (D:\IdeaProjects\FastGPT-main\client\node_modules\next\dist\server\api-utils\node.js:372:9)
    at async DevServer.runApi (D:\IdeaProjects\FastGPT-main\client\node_modules\next\dist\server\next-server.js:488:9)
    at async Object.fn (D:\IdeaProjects\FastGPT-main\client\node_modules\next\dist\server\next-server.js:751:37)
    at async Router.execute (D:\IdeaProjects\FastGPT-main\client\node_modules\next\dist\server\router.js:253:36)
    at async DevServer.run (D:\IdeaProjects\FastGPT-main\client\node_modules\next\dist\server\base-server.js:384:29)
    at async DevServer.run (D:\IdeaProjects\FastGPT-main\client\node_modules\next\dist\server\dev\next-dev-server.js:743:20)
    at async DevServer.handleRequest (D:\IdeaProjects\FastGPT-main\client\node_modules\next\dist\server\base-server.js:322:20) {
  length: 108,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '28',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1392',
  routine: 'parserOpenTable'
}

![image](https://github.com/labring/FastGPT/assets/46702672/a79fd686-9fe3-4eea-8578-b0dba863d688)

**Comment by ChafLee** [comment]
解决了，init.sql里是大写modelData，改成小写modeldata就好了

**Comment by varnew** [comment]
> 解决了，init.sql里是大写modelData，改成小写modeldata就好了

请问下是，脚本里面所有的modelData改成modeldata吗

**Comment by c121914yu** [comment]
感谢。已更新。
部分系统会自动把大写转小写，没注意到兼容问题，已全改小写。
