### ISSUE TITLE
做向量重排时出错

### ISSUE THREAD

**Issue by cq134cq** [labring/FastGPT#1271]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.7
- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 
docker 
**问题描述**
做向量重排时出错
**复现步骤**

**预期结果**

**相关截图**
![3F934C0A-7D47-44ff-87A9-AC3980EE362A](https://github.com/labring/FastGPT/assets/95132993/2313f6cc-25bb-403b-b3c5-11a20e8bf7f0)
![9EFEE5C4-9C16-42f0-AF4C-012E1BAF92B6](https://github.com/labring/FastGPT/assets/95132993/919def41-f33f-4882-89e0-4040619cc354)
rerank error: AxiosError: timeout of 30000ms exceeded
at RedirectableRequest.handleRequestTimeout (file:///app/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/adapters/http.js:647:16)
at RedirectableRequest.emit (node:events:514:28)
at Timeout. (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:210:12)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
at Axios.request (file:///app/node_modules/.pnpm/axios@1.6.8/node_modules/axios/lib/core/Axios.js:45:41)
at async q (/app/projects/app/.next/server/chunks/59120.js:85:3465)
at async g (/app/projects/app/.next/server/chunks/59120.js:86:957)
at async /app/projects/app/.next/server/pages/api/core/dataset/searchTest.js:1:2983 {
code: 'ECONNABORTED',
config: {
transitional: {
silentJSONParsing: true,
forcedJSONParsing: true,
clarifyTimeoutError: false
},
adapter: [ 'xhr', 'http' ],
transformRequest: [ [Function: transformRequest] ],
transformResponse: [ [Function: transformResponse] ],
timeout: 30000,
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
env: { FormData: [Function], Blob: [class Blob] },
validateStatus: [Function: validateStatus],
headers: Object [AxiosHeaders] {
Accept: 'application/json, text/plain, /',
'Content-Type': 'application/json',
'Cache-Control': 'no-cache',
Authorization: 'Bearer mytoken',
'User-Agent': 'axios/1.6.8',
'Content-Length': '61742',
'Accept-Encoding': 'gzip, compress, deflate, br'
},
baseURL: 'http://2a1826918fd7:3000/',
url: 'http://10.0.100.190:6006/v1/rerank',
method: 'post',
请问这个是时间太短？

**Comment by cq134cq** [comment]
?

**Comment by c121914yu** [comment]
没gpu太慢了

**Comment by cq134cq** [comment]
> gpu太慢了

请问可以调用外部的向量模型吗？
