### ISSUE TITLE
对接chatgpt-on-wechat后，对话报错

### ISSUE THREAD

**Issue by cuisws** [labring/FastGPT#1280]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述**
对接chatgpt-on-wechat聊天时报错，返回的错误信息如下：
[CHATGPT] Bad Gateway: Invalid response object from API: '{"code":500,"statusText":"","message":"messages: Unexpected role \\"system\\". The Messages API accepts a top-level `system` parameter, not \\"system\\" as an input message role. (request id: 2024042406551098314045715094124)","data":null}' (HTTP response code was 500)
**复现步骤**

**预期结果**

**相关截图**
这是fastgpt里面的错误信息：
{
2024-04-24 14:55:33   message: '400 messages: Unexpected role "system". The Messages API accepts a top-level `system` parameter, not "system" as an input message role. (request id: 2024042406553358995318792461046)',
2024-04-24 14:55:33   stack: 'Error: 400 messages: Unexpected role "system". The Messages API accepts a top-level `system` parameter, not "system" as an input message role. (request id: 2024042406553358995318792461046)\n' +
2024-04-24 14:55:33     '    at eI.generate (/app/projects/app/.next/server/chunks/28687.js:25:70043)\n' +
2024-04-24 14:55:33     '    at af.makeStatusError (/app/projects/app/.next/server/chunks/28687.js:25:81687)\n' +
2024-04-24 14:55:33     '    at af.makeRequest (/app/projects/app/.next/server/chunks/28687.js:25:82610)\n' +
2024-04-24 14:55:33     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-04-24 14:55:33     '    at async Object.x [as chatNode] (/app/projects/app/.next/server/chunks/60913.js:129:1124)\n' +
2024-04-24 14:55:33     '    at async $ (/app/projects/app/.next/server/chunks/60913.js:130:2838)\n' +
2024-04-24 14:55:33     '    at async Promise.all (index 0)\n' +
2024-04-24 14:55:33     '    at async Promise.all (index 0)\n' +
2024-04-24 14:55:33     '    at async Promise.all (index 0)\n' +
2024-04-24 14:55:33     '    at async b (/app/projects/app/.next/server/chunks/60913.js:130:4167)\n' +
2024-04-24 14:55:33     '    at async /app/projects/app/.next/server/pages/api/v1/chat/completions.js:1:4238'
2024-04-24 14:55:33 }

**Comment by cuisws** [comment]
我是本地容器运行，最新版本4.7.1，我看到one api日志显示我对话时请求的是text-embedding-ada-002模型，不知道为什么。这个应用模型设置的是claude，fastgpt对话是正常的。

**Comment by cuisws** [comment]
解决了，根据报错信息误打误撞试了一下，把chatgpt-on-wechat中的character_desc和subscribe_msg值设置为空字符串。

**Comment by nianyi-778** [comment]
> 解决了，根据报错信息误打误撞试了一下，把chatgpt-on-wechat中的character_desc和subscribe_msg值设置为空字符串。

什么原理啊
