### ISSUE TITLE
@node-rs/jieba 缺失

### ISSUE THREAD

**Issue by bincooo** [labring/FastGPT#1311]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 
docker-compose: ghcr.io/labring/fastgpt:v4.8-preview3

**问题描述**
RT
全新部署，登陆界面点击登陆后出现
```js
}
Error: Cannot find module '@node-rs/jieba'
Require stack:
- /app/projects/app/.next/server/pages/api/common/system/getInitData.js
- /app/node_modules/.pnpm/next@13.5.2_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/future/helpers/module-loader/node-module-loader.js
- /app/node_modules/.pnpm/next@13.5.2_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/future/helpers/module-loader/route-module-loader.js
- /app/node_modules/.pnpm/next@13.5.2_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/next-server.js
- /app/node_modules/.pnpm/next@13.5.2_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/next.js
- /app/projects/app/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /app/node_modules/.pnpm/next@13.5.2_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/app/node_modules/.pnpm/next@13.5.2_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:121:18)
    at 85720 (/app/projects/app/.next/server/pages/api/common/system/getInitData.js:1:512)
    at o (/app/projects/app/.next/server/webpack-api-runtime.js:1:128)
    at 61292 (/app/projects/app/.next/server/chunks/97274.js:127:1876)
    at o (/app/projects/app/.next/server/webpack-api-runtime.js:1:128)
    at /app/projects/app/.next/server/chunks/97274.js:298:27116
    at o.a (/app/projects/app/.next/server/webpack-api-runtime.js:1:879)
    at 58943 (/app/projects/app/.next/server/chunks/97274.js:298:27021)
    at o (/app/projects/app/.next/server/webpack-api-runtime.js:1:128)
    at /app/projects/app/.next/server/chunks/97274.js:300:827
    at o.a (/app/projects/app/.next/server/webpack-api-runtime.js:1:879) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/projects/app/.next/server/pages/api/common/system/getInitData.js',
    '/app/node_modules/.pnpm/next@13.5.2_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/future/helpers/module-loader/node-module-loader.js',
    '/app/node_modules/.pnpm/next@13.5.2_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/future/helpers/module-loader/route-module-loader.js',
    '/app/node_modules/.pnpm/next@13.5.2_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/next-server.js',
    '/app/node_modules/.pnpm/next@13.5.2_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/next.js',
    '/app/projects/app/server.js'
  ]
}


```

**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
+1 
![image](https://github.com/labring/FastGPT/assets/156336589/63a8ee48-0e1c-4a91-b05a-54c519bd7a86)
![image](https://github.com/labring/FastGPT/assets/156336589/67a414c1-20ae-4b00-88ee-c537db34d9b2)

**Comment by c121914yu** [comment]
我看看，有点神奇，都能build了

**Comment by c121914yu** [comment]
action中，，这库有点神奇，，必须在主项目中安装。。
