### ISSUE TITLE
应用知识库检索超时，504 Gateway Time-out，知识库向量化正常。

### ISSUE THREAD

**Issue by Code-Bai** [labring/FastGPT#1686]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
![image](https://github.com/labring/FastGPT/assets/62536222/cdb7b227-df44-4a4e-afd5-22bb2c1a641c)
![image](https://github.com/labring/FastGPT/assets/62536222/04366973-5524-4141-b120-31c481252689)
```
[Error] 2024-06-04 07:42:26 sse error: 504 <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.21.4</center>
</body>
</html>
 
{
  message: '504 <html>\r\n' +
    '<head><title>504 Gateway Time-out</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>504 Gateway Time-out</h1></center>\r\n' +
    '<hr><center>nginx/1.21.4</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n',
  stack: 'Error: 504 <html>\r\n' +
    '<head><title>504 Gateway Time-out</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>504 Gateway Time-out</h1></center>\r\n' +
    '<hr><center>nginx/1.21.4</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n' +
    '\n' +
    '    at eI.generate (/app/projects/app/.next/server/chunks/83985.js:15:67761)\n' +
    '    at av.makeStatusError (/app/projects/app/.next/server/chunks/83985.js:15:79337)\n' +
    '    at av.makeRequest (/app/projects/app/.next/server/chunks/83985.js:15:80260)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async d (/app/projects/app/.next/server/chunks/75612.js:250:214)\n' +
    '    at async /app/projects/app/.next/server/chunks/75612.js:253:253\n' +
    '    at async l (/app/projects/app/.next/server/chunks/75612.js:253:214)\n' +
    '    at async Object.p [as datasetSearchNode] (/app/projects/app/.next/server/chunks/75612.js:312:4362)\n' +
    '    at async k (/app/projects/app/.next/server/chunks/75612.js:313:2231)\n' +
    '    at async Promise.all (index 0)'
}
```
**复现步骤**

**预期结果**

**相关截图**

**Comment by lijiajun1997** [comment]
看下是不是mongoDB挂了或者重启了

**Comment by c121914yu** [comment]
模型挂了吧
