### ISSUE TITLE
4.7.1到4.8.1升级中日志报错误

### ISSUE THREAD

**Issue by gaord** [labring/FastGPT#1745]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.7.1

**问题描述, 日志截图**
按照升级步骤，运行：
curl --location --request POST 'http://localhost:3000/api/admin/initv481' \ 
--header 'rootkey: root_key' \   
--header 'Content-Type: application/json'
{"code":200,"statusText":"","message":"success","data":null}%  

4.7.1->4.8.1升级过程中出现以下错误，界面观察正常，不知道有什么影响：
2024-06-12 13:27:20 pg connected
2024-06-12 13:27:20 init pg error error: column "createtime" does not exist
2024-06-12 13:27:20     at /app/projects/app/.next/server/chunks/15428.js:9:532499
2024-06-12 13:27:20     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-12 13:27:20     at async l (/app/projects/app/.next/server/chunks/75612.js:143:306)
2024-06-12 13:27:20     at async Promise.all (index 0)
2024-06-12 13:27:20     at async afterHook (/app/projects/app/.next/server/chunks/75612.js:312:4420)
2024-06-12 13:27:20     at async r (/app/projects/app/.next/server/chunks/75612.js:130:19963)
2024-06-12 13:27:20     at async Promise.all (index 1)
2024-06-12 13:27:20     at async /app/projects/app/.next/server/pages/api/admin/initv481.js:1:5036
2024-06-12 13:27:20     at async K (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
2024-06-12 13:27:20     at async U.render (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492) {
2024-06-12 13:27:20   length: 100,
2024-06-12 13:27:20   severity: 'ERROR',
2024-06-12 13:27:20   code: '42703',
2024-06-12 13:27:20   detail: undefined,
2024-06-12 13:27:20   hint: undefined,
2024-06-12 13:27:20   position: undefined,
2024-06-12 13:27:20   internalPosition: undefined,
2024-06-12 13:27:20   internalQuery: undefined,
2024-06-12 13:27:20   where: undefined,
2024-06-12 13:27:20   schema: undefined,
2024-06-12 13:27:20   table: undefined,
2024-06-12 13:27:20   column: undefined,
2024-06-12 13:27:20   dataType: undefined,
2024-06-12 13:27:20   constraint: undefined,
2024-06-12 13:27:20   file: 'indexcmds.c',
2024-06-12 13:27:20   line: '1848',
2024-06-12 13:27:20   routine: 'ComputeIndexAttrs'
2024-06-12 13:27:20 }
2024-06-12 13:27:20 retry init root user
2024-06-12 13:27:20 create default team new ObjectId("6571cec916b8caae04ebffc3")
2024-06-12 13:27:20 root user init: { username: 'root', password: '1234' }
2024-06-12 13:27:20 [INFO] 2024-06-12 05:27:20 [QA Queue] Done 
2024-06-12 13:27:20 [INFO] 2024-06-12 05:27:20 [Vector Queue] Done 
2024-06-12 13:27:20 success rename dataset.trainings -> dataset_trainings
2024-06-12 13:27:20 success rename dataset.collections -> dataset_collections
2024-06-12 13:27:20 success rename dataset.datas -> dataset_datas
2024-06-12 13:27:20 success rename app.versions -> app_versions
2024-06-12 13:27:20 success rename buffer.rawtexts -> buffer_rawtexts
2024-06-12 13:27:20 success rename team.members -> team_members
2024-06-12 13:27:20 success rename team.subscriptions -> team_subscriptions
2024-06-12 13:27:20 [INFO] 2024-06-12 05:27:20 Request finish /api/admin/initv481, time: 551ms 
2024-06-12 13:28:00 [INFO] 2024-06-12 05:28:00 [QA Queue] Done 
2024-06-12 13:28:00 [INFO] 2024-06-12 05:28:00 [Vector Queue] Done
**复现步骤**

**预期结果**
升级时没有错误日志
**相关截图**

**Comment by c121914yu** [comment]
可能是以前漏了某个版本初始化，没把 createtime 字段初始化~ 参考下面字段，手段创建 createtime 列。
```
CREATE TABLE IF NOT EXISTS ${DatasetVectorTableName} (
            id BIGSERIAL PRIMARY KEY,
            vector VECTOR(1536) NOT NULL,
            team_id VARCHAR(50) NOT NULL,
            dataset_id VARCHAR(50) NOT NULL,
            collection_id VARCHAR(50) NOT NULL,
            createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
```

**Comment by gaord** [comment]
谢谢大佬
