### ISSUE TITLE
在进行登陆时报错

### ISSUE THREAD

**Issue by TCHSDUFH** [labring/FastGPT#1753]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.3

**问题描述, 日志截图**
登录时报错 账号密码为默认的root/1234
![123](https://github.com/labring/FastGPT/assets/58661545/90733ffd-86b9-48a7-a8eb-2641517f8f3e)
后台提示如下：
`
 Compiled /api/support/user/account/loginByPassword in 331ms (1972 modules)
error-> mongo connect error MongooseServerSelectionError: getaddrinfo EAI_AGAIN mongo
    at _handleConnectionErrors (webpack-internal:///(api)/../../node_modules/.pnpm/mongoose@7.0.2/node_modules/mongoose/lib/connection.js:755:11)
    at NativeConnection.openUri (webpack-internal:///(api)/../../node_modules/.pnpm/mongoose@7.0.2/node_modules/mongoose/lib/connection.js:730:11)
    at async connectMongo (webpack-internal:///(api)/../../packages/service/common/mongo/init.ts:19:9)
    at async getInitConfig (webpack-internal:///(api)/./src/pages/api/common/system/getInitData.ts:69:9)
    at async handler (webpack-internal:///(api)/./src/pages/api/common/system/getInitData.ts:32:5)
    at async K (/home/htc/Desktop/fastGptTest/fastGPT/FastGPT/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2871)
    at async U.render (/home/htc/Desktop/fastGptTest/fastGPT/FastGPT/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3955)
    at async DevServer.runApi (/home/htc/Desktop/fastGptTest/fastGPT/FastGPT/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/home/htc/Desktop/fastGptTest/fastGPT/FastGPT/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/next-server.js:269:37)
    at async DevServer.handleRequestImpl (/home/htc/Desktop/fastGptTest/fastGPT/FastGPT/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/base-server.js:816:17)
    at async /home/htc/Desktop/fastGptTest/fastGPT/FastGPT/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/home/htc/Desktop/fastGptTest/fastGPT/FastGPT/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/home/htc/Desktop/fastGptTest/fastGPT/FastGPT/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/home/htc/Desktop/fastGptTest/fastGPT/FastGPT/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/home/htc/Desktop/fastGptTest/fastGPT/FastGPT/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/lib/router-server.js:353:24) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(1) { 'mongo:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'rs0',
    maxElectionId: new ObjectId("7fffffff0000000000000002"),
    maxSetVersion: 1,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
System Version: 4.8.3
{
  feConfigs: {
    lafEnv: 'https://laf.dev',
    show_emptyChat: true,
    show_git: true,
    docUrl: 'https://doc.fastgpt.in',
    openAPIDocUrl: 'https://doc.fastgpt.in/docs/development/openapi',
    systemTitle: 'FastGPT',
    concatMd: '项目开源地址: [FastGPT GitHub](https://github.com/labring/FastGPT)\n' +
      '交流群: ![](https://oss.laf.run/htr4n1-images/fastgpt-qr-code.jpg)',
    limit: { exportDatasetLimitMinutes: 0, websiteSyncLimitMinuted: 0 },
    scripts: [],
    favicon: '/favicon.ico',
    uploadFileMaxSize: 500,
    isPlus: false
  },
  systemEnv: {
    openapiPrefix: 'fastgpt',
    vectorMaxProcess: 15,
    qaMaxProcess: 15,
    pgHNSWEfSearch: 100,
    tokenWorkers: 20
  },
  subPlans: undefined,
  llmModels: [
    {
      model: 'gpt-3.5-turbo',
      name: 'gpt-3.5-turbo',
      maxContext: 16000,
      avatar: '/imgs/model/openai.svg',
      maxResponse: 4000,
      quoteMaxToken: 13000,
      maxTemperature: 1.2,
      charsPointsPrice: 0,
      censor: false,
      vision: false,
      datasetProcess: true,
      usedInClassify: true,
      usedInExtractFields: true,
      usedInToolCall: true,
      usedInQueryExtension: true,
      toolChoice: true,
      functionCall: true,
      customCQPrompt: '',
      customExtractPrompt: '',
      defaultSystemChatPrompt: '',
      defaultConfig: {}
    },
    {
      model: 'gpt-4-0125-preview',
      name: 'gpt-4-turbo',
      avatar: '/imgs/model/openai.svg',
      maxContext: 125000,
      maxResponse: 4000,
      quoteMaxToken: 100000,
      maxTemperature: 1.2,
      charsPointsPrice: 0,
      censor: false,
      vision: false,
      datasetProcess: false,
      usedInClassify: true,
      usedInExtractFields: true,
      usedInToolCall: true,
      usedInQueryExtension: true,
      toolChoice: true,
      functionCall: false,
      customCQPrompt: '',
      customExtractPrompt: '',
      defaultSystemChatPrompt: '',
      defaultConfig: {}
    },
    {
      model: 'gpt-4-vision-preview',
      name: 'gpt-4-vision',
      avatar: '/imgs/model/openai.svg',
      maxContext: 128000,
      maxResponse: 4000,
      quoteMaxToken: 100000,
      maxTemperature: 1.2,
      charsPointsPrice: 0,
      censor: false,
      vision: true,
      datasetProcess: false,
      usedInClassify: false,
      usedInExtractFields: false,
      usedInToolCall: false,
      usedInQueryExtension: false,
      toolChoice: true,
      functionCall: false,
      customCQPrompt: '',
      customExtractPrompt: '',
      defaultSystemChatPrompt: '',
      defaultConfig: {}
    }
  ],
  vectorModels: [
    {
      model: 'text-embedding-3-large',
      name: 'Embedding-3-large',
      avatar: '/imgs/model/openai.svg',
      charsPointsPrice: 0,
      defaultToken: 512,
      maxToken: 3000,
      weight: 100,
      dbConfig: {},
      queryConfig: {},
      defaultConfig: [Object]
    },
    {
      model: 'text-embedding-3-small',
      name: 'Embedding-3-small',
      avatar: '/imgs/model/openai.svg',
      charsPointsPrice: 0,
      defaultToken: 512,
      maxToken: 3000,
      weight: 100,
      dbConfig: {},
      queryConfig: {}
    },
    {
      model: 'text-embedding-ada-002',
      name: 'text-embedding-ada-002',
      avatar: '/imgs/model/openai.svg',
      charsPointsPrice: 0,
      defaultToken: 512,
      maxToken: 3000,
      weight: 100,
      dbConfig: {},
      queryConfig: {}
    }
  ],
  reRankModels: [],
  audioSpeechModels: [
    {
      model: 'tts-1',
      name: 'OpenAI TTS1',
      charsPointsPrice: 0,
      voices: [Array]
    }
  ],
  whisperModel: { model: 'whisper-1', name: 'Whisper1', charsPointsPrice: 0 }
}
{
  communityPlugins: [
    {
      author: 'FastGPT Team',
      templateType: 'tools',
      name: '文本加工',
      avatar: '/imgs/workflow/textEditor.svg',
      intro: '可对固定或传入的文本进行加工后输出，非字符串类型数据最终会转成字符串类型。',
      showStatus: false,
      isTool: false,
      weight: 100,
      nodes: [Array],
      edges: [Array],
      id: 'community-textEditor',
      source: 'community'
    },
    {
      author: 'FastGPT Team',
      templateType: 'tools',
      name: '获取当前时间',
      avatar: '/imgs/workflow/getCurrentTime.svg',
      intro: '获取用户当前时区的时间。',
      showStatus: false,
      isTool: true,
      weight: 10,
      nodes: [Array],
      edges: [Array],
      id: 'community-getCurrentTime',
      source: 'community'
    },
    {
      author: 'FastGPT Team',
      templateType: 'other',
      name: '自定义反馈',
      avatar: '/imgs/workflow/customFeedback.svg',
      intro: '该模块被触发时，会给当前的对话记录增加一条反馈。可用于自动记录对话效果等。',
      showStatus: false,
      isTool: false,
      weight: 0,
      nodes: [Array],
      edges: [Array],
      id: 'community-customFeedback',
      source: 'community'
    }
  ]
}
[Error] 2024-06-13 13:33:30 Api response error: undefined, Operation `users.findOne()` buffering timed out after 10000ms 
{
  message: 'Operation `users.findOne()` buffering timed out after 10000ms',
  stack: 'MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n' +
    '    at Timeout.eval (webpack-internal:///(api)/../../node_modules/.pnpm/mongoose@7.0.2/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)\n' +
    '    at listOnTimeout (node:internal/timers:573:17)\n' +
    '    at process.processTimers (node:internal/timers:514:7)'
}
 POST /api/support/user/account/loginByPassword 500 in 10462ms
`
在docker中查看状态，发现one-api一直在重启
![42343](https://github.com/labring/FastGPT/assets/58661545/cca0f2fc-54a7-42d3-ad5c-84936d69ecc6)

**复现步骤**

**预期结果**

**相关截图**

**Comment by TCHSDUFH** [comment]
通过查看onapi的日志发现
![Snipaste_2024-06-13_14-18-48](https://github.com/labring/FastGPT/assets/58661545/0e21f541-ea71-4323-a6a7-c9fb190b9dd9)
一直无法连上mysql
