### ISSUE TITLE
数据库能否和fastgpt分开部署

### ISSUE THREAD

**Issue by chiheye** [labring/FastGPT#1765]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [ x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 4.8.3

**问题描述, 日志截图**
数据库能否和fastgpt分开部署，测试分开部署后fastgpt无法连接到mongodb
mongodb地址已修改成mongodb://myusername:mypassword@192.168.31.57:27017/fastgpt?authSource=admin(去掉?authSource=admin也不行)
**复现步骤**
直接修改de docker-compose.yml
version: '3.3'
services:
  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:v4.8.3
    ports:
      - 3000:3000
    networks:
      - fastgpt
    restart: always
    environment:
      # root 密码，用户名为: root。如果需要修改 root 密码，直接修改这个环境变量，并重启即可。
      - DEFAULT_ROOT_PSW=root
      # AI模型的API地址哦。务必加 /v1。这里默认填写了OneApi的访问地址。
      - OPENAI_BASE_URL=http://192.168.31.73:16106/v1
      # AI模型的API Key。
      - CHAT_API_KEY=sk-4B2TstGWWWssUYFtCbBs2bE75a0a4s5fAa2900Ca730e2e7b
      # 数据库最大连接数
      - DB_MAX_LINK=5
      # 登录凭证密钥
      - TOKEN_KEY=75fBbC7F0C1
      # root的密钥，常用于升级时候的初始化请求
      - ROOT_KEY=75fBbC7F0C1
      # 文件阅读加密
      - FILE_TOKEN_KEY=75fBbC7F0C1
      # MongoDB 连接参数. 用户名myusername,密码mypassword。
      - MONGODB_URI=mongodb://myusername:mypassword@192.168.31.57:27017/fastgpt?authSource=admin
      # pg 连接参数
      - PG_URL=postgresql://username:password@192.168.31.57:5432/postgres
    volumes:
      - ./config.json:/app/data/config.json
      - ./fastgpt/tmp:/app/tmp
      - ./fastgpt/docs:/app/projects/app/public/docs
networks:
  fastgpt:
下面是报错信息
▲ Next.js 14.2.3
  - Local:        http://5996d8dd3bc4:3000
  - Network:      http://172.20.0.2:3000

 ✓ Starting...
 ✓ Ready in 670ms
mongo start connect
error-> mongo connect error u [MongooseServerSelectionError]: getaddrinfo ENOTFOUND mongo
    at S (/app/projects/app/.next/server/chunks/36016.js:40:71)
    at O.openUri (/app/projects/app/.next/server/chunks/36016.js:48:1206)
    at async r (/app/projects/app/.next/server/chunks/75612.js:134:19581)
    at async x (/app/projects/app/.next/server/pages/api/support/user/account/loginByPassword.js:1:2848)
    at async K (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
    at async U.render (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/next-server.js:600:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/next-server.js:269:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/base-server.js:816:17)
    at async invokeRender (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.24.4_react-dom@18.3.1_react@18.3.1_sass@1.58.3/node_modules/next/dist/server/lib/router-server.js:174:21) {
  reason: m {
    type: 'ReplicaSetNoPrimary',
    servers: Map(1) { 'mongo:27017' => [l] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'rs0',
    maxElectionId: new ObjectId("7fffffff0000000000000006"),
    maxSetVersion: 1,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
[Error] 2024-06-14 05:34:17 Api response error: undefined, Operation `users.findOne()` buffering timed out after 10000ms 
{
  message: 'Operation `users.findOne()` buffering timed out after 10000ms',
  stack: 'MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n' +
    '    at Timeout.<anonymous> (/app/projects/app/.next/server/chunks/36016.js:139:1390)\n' +
    '    at listOnTimeout (node:internal/timers:569:17)\n' +
    '    at process.processTimers (node:internal/timers:512:7)'
}
**预期结果**
希望数据库能和fastgpt分开部署
**相关截图**
![Screenshot 2024-06-14 at 1 35 54 PM](https://github.com/labring/FastGPT/assets/42902754/82f16ff6-4e83-4348-a2de-9a8ec15e3fee)

**Comment by c121914yu** [comment]
网络问题，自己补 docker 知识
