### ISSUE TITLE
有没有完整的milvus带有token的例子?

### ISSUE THREAD

**Issue by jqlts1** [labring/FastGPT#1839]
我本地安装的milvus确定是完全没有任何问题的,可以正常使用
但是不管我的docker-compose怎么配置都会报错....
我也不知道自己哪里写错了...官方也有没有带有token的写法... 或是使用自定义的milvus远程连接

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/c48416dc-d821-4641-8edd-ae06bd86ecfa)
根据mivlus官方介绍，token就是用户名+密码。

**Comment by jqlts1** [comment]
<img width="723" alt="image" src="https://github.com/labring/FastGPT/assets/17434370/c8f72ced-0950-4edf-a0a7-2105373f2958">

我这本本地是可以链接( 当然我没有加入 token ) ,但是
<img width="437" alt="image" src="https://github.com/labring/FastGPT/assets/17434370/a498746b-10c8-414d-bc96-d8ee11aaf928">


 我这样设置了以后,就会提示
```shell
fastgpt_test    | [Info] 2024-06-25 08:25:18 Milvus connected 
fastgpt_test    | Error: 14 UNAVAILABLE: Failed to parse DNS address dns:"127.0.0.1:19530"
fastgpt_test    |     at callErrorFromStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.10.8/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
fastgpt_test    |     at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.10.8/node_modules/@grpc/grpc-js/build/src/client.js:193:76)
fastgpt_test    |     at /app/node_modules/.pnpm/@grpc+grpc-js@1.10.8/node_modules/@grpc/grpc-js/build/src/call-interface.js:78:35
fastgpt_test    |     at Object.onReceiveStatus (/app/node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.4.2/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Grpc.js:146:25)
fastgpt_test    |     at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.10.8/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
fastgpt_test    |     at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.10.8/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
fastgpt_test    |     at /app/node_modules/.pnpm/@grpc+grpc-js@1.10.8/node_modules/@grpc/grpc-js/build/src/resolving-call.js:129:78
fastgpt_test    |     at processTicksAndRejections (node:internal/process/task_queues:77:11)
fastgpt_test    |     at runNextTicks (node:internal/process/task_queues:64:3)
fastgpt_test    |     at process.processImmediate (node:internal/timers:447:9)
fastgpt_test    | for call at
fastgpt_test    |     at ServiceClientImpl.makeUnaryRequest (/app/node_modules/.pnpm/@grpc+grpc-js@1.10.8/node_modules/@grpc/grpc-js/build/src/client.js:161:32)
fastgpt_test    |     at ServiceClientImpl.<anonymous> (/app/node_modules/.pnpm/@grpc+grpc-js@1.10.8/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
fastgpt_test    |     at /app/node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.4.2/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:32:31
fastgpt_test    |     at new Promise (<anonymous>)
fastgpt_test    |     at /app/node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.4.2/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:29:16
fastgpt_test    |     at Generator.next (<anonymous>)
fastgpt_test    |     at fulfilled (/app/node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.4.2/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:5:58)
fastgpt_test    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
fastgpt_test    |   code: 14,
fastgpt_test    |   details: 'Failed to parse DNS address dns:"127.0.0.1:19530"',
fastgpt_test    |   metadata: Metadata { internalRepr: Map(0) {}, options: {} }
```

**Comment by jqlts1** [comment]
对了,我的 mongo 是正常的,因为我把 milvus 的链接注销掉,一切都全部正常了,但是如果使用了 milvus 就会出现这个问题

**Comment by c121914yu** [comment]
> 对了,我的 mongo 是正常的,因为我把 milvus 的链接注销掉,一切都全部正常了,但是如果使用了 milvus 就会出现这个问题

和 mongo 没关系，向量库连不上，mongo 连接就会抛错。而且 127.0.0.1 肯定是连不上的，这是容器网络，不是 host。

**Comment by jqlts1** [comment]
> > 对了,我的 mongo 是正常的,因为我把 milvus 的链接注销掉,一切都全部正常了,但是如果使用了 milvus 就会出现这个问题
> 
> 和 mongo 没关系，向量库连不上，mongo 连接就会抛错。而且 127.0.0.1 肯定是连不上的，这是容器网络，不是 host。

但是我用域名也不行,我外部都可以访问到我的向量数据库了,而且还可以直接操作,但是fastgpt 就生一直链接不上

**Comment by c121914yu** [comment]
> > > 对了,我的 mongo 是正常的,因为我把 milvus 的链接注销掉,一切都全部正常了,但是如果使用了 milvus 就会出现这个问题
> > 
> > 和 mongo 没关系，向量库连不上，mongo 连接就会抛错。而且 127.0.0.1 肯定是连不上的，这是容器网络，不是 host。
> 
> 但是我用域名也不行,我外部都可以访问到我的向量数据库了,而且还可以直接操作,但是fastgpt 就生一直链接不上

那不清楚了，我这远程部署就是按上面参数链接即可，地址是服务器 ip。
