### ISSUE TITLE
不能新建应用，提示MongoServerError

### ISSUE THREAD

**Issue by stephenlzc** [labring/FastGPT#1967]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本, 具体版本号: V4.8.5

**问题描述, 日志截图**
##1、无法创建应用
<img width="1264" alt="image" src="https://github.com/labring/FastGPT/assets/52523593/2e491ae3-e445-47bf-9cce-8edcd463f267">

##2、上传文件后一直不能下一步
<img width="1255" alt="image" src="https://github.com/labring/FastGPT/assets/52523593/71aca9f0-2cec-4b79-9871-5608a50870ac">

**复现步骤**
1、系统配置，全新安装的系统，

> CPU:12th Gen Intel(R) Core(TM) i7-12700K   3.60 GHz
RAM：64.0 GB
OS：Windows 11 专业版 23H2
WSL：Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
Docker:Current version: 4.31.1 (153621) 已开启WSL integration和Use the WSL 2 based engine

2、已经通过以下两个文件启动docker

[docker-compose.yml](https://github.com/stephenlzc/voicememo/blob/f3611ffc4cf88e5964784d58422b22f7ca1fdfee/docker-compose.yml)
[config.json](https://github.com/user-attachments/files/16106811/config.json)
<img width="1457" alt="image" src="https://github.com/labring/FastGPT/assets/52523593/8f214ce5-b301-4cff-ac8f-07e54f541c40">

3、相关Log
当点击创建应用时：

> `2024-07-05 16:06:22 mongo    | {"t":{"$date":"2024-07-05T08:06:22.311+00:00"},"s":"I",  "c":"STORAGE",  "id":20320,   "ctx":"conn586","msg":"createCollection","attr":{"namespace":"fastgpt.app_versions","uuidDisposition":"generated","uuid":{"uuid":{"$uuid":"63fffa04-1507-4c3f-af2f-8f0aa78343d0"}},"options":{}}}
2024-07-05 16:06:22 mongo    | {"t":{"$date":"2024-07-05T08:06:22.315+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"conn586","msg":"WiredTiger error","attr":{"error":1,"message":"[1720166782:315269][10:0x7f65334f5700], WT_SESSION.create: __posix_open_file, 815: /data/db/collection-13--4210291667907924385.wt: handle-open: open: Operation not permitted"}}
2024-07-05 16:06:22 fastgpt  | [Error] 2024-07-05 08:06:22 Api response error: /api/core/app/create, 1: Operation not permitted 
2024-07-05 16:06:22 fastgpt  | {
2024-07-05 16:06:22 fastgpt  |   message: '1: Operation not permitted',
2024-07-05 16:06:22 fastgpt  |   stack: 'MongoServerError: 1: Operation not permitted\n' +
2024-07-05 16:06:22 fastgpt  |     '    at /app/projects/app/.next/server/chunks/36016.js:6:279520\n' +
2024-07-05 16:06:22 fastgpt  |     '    at /app/projects/app/.next/server/chunks/36016.js:6:137694\n' +
2024-07-05 16:06:22 fastgpt  |     '    at /app/projects/app/.next/server/chunks/36016.js:6:311803\n' +
2024-07-05 16:06:22 fastgpt  |     '    at /app/projects/app/.next/server/chunks/36016.js:6:310782\n' +
2024-07-05 16:06:22 fastgpt  |     '    at S.onMessage (/app/projects/app/.next/server/chunks/36016.js:6:128592)\n' +
2024-07-05 16:06:22 fastgpt  |     '    at c.<anonymous> (/app/projects/app/.next/server/chunks/36016.js:6:126416)\n' +
2024-07-05 16:06:22 fastgpt  |     '    at c.emit (node:events:514:28)\n' +
2024-07-05 16:06:22 fastgpt  |     '    at e (/app/projects/app/.next/server/chunks/36016.js:6:145742)\n' +
2024-07-05 16:06:22 fastgpt  |     '    at c._write (/app/projects/app/.next/server/chunks/36016.js:6:146155)\n' +
2024-07-05 16:06:22 fastgpt  |     '    at writeOrBuffer (node:internal/streams/writable:392:12)'
2024-07-05 16:06:22 fastgpt  | }
2024-07-05 16:06:22 oneapi   | [SYS] 2024/07/05 - 08:06:22 | batch update started 
2024-07-05 16:06:22 oneapi   | [SYS] 2024/07/05 - 08:06:22 | batch update finished 
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.623+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn591","msg":"Connection ended","attr":{"remote":"172.19.0.6:55048","uuid":"37f8437c-5cb8-4daa-9f9d-7ef3caf7b00e","connectionId":591,"connectionCount":46}}
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.721+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.19.0.6:47678","uuid":"05d86d09-a820-4539-98a3-5609248c4128","connectionId":625,"connectionCount":47}}
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.723+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn625","msg":"client metadata","attr":{"remote":"172.19.0.6:47678","client":"conn625","doc":{"driver":{"name":"nodejs|Mongoose","version":"5.1.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.153.1-microsoft-standard-WSL2"},"platform":"Node.js v18.17.1, LE (unified)","version":"5.1.0|7.0.2"}}}
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.726+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn625","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"myusername","authenticationDatabase":"admin","remote":"172.19.0.6:47678","extraInfo":{}}}
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.727+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn592","msg":"Connection ended","attr":{"remote":"172.19.0.6:55054","uuid":"377956ee-fae6-40c8-ade4-ebe638892b82","connectionId":592,"connectionCount":46}}
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.828+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.19.0.6:47684","uuid":"553280a3-bb0a-4289-aca2-47395329d091","connectionId":626,"connectionCount":47}}
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.828+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn593","msg":"Connection ended","attr":{"remote":"172.19.0.6:55068","uuid":"d52b69f6-fa84-4f1b-b2a5-e22e95db9fff","connectionId":593,"connectionCount":46}}
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.828+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn626","msg":"client metadata","attr":{"remote":"172.19.0.6:47684","client":"conn626","doc":{"driver":{"name":"nodejs|Mongoose","version":"5.1.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.153.1-microsoft-standard-WSL2"},"platform":"Node.js v18.17.1, LE (unified)","version":"5.1.0|7.0.2"}}}
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.829+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn626","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"myusername","authenticationDatabase":"admin","remote":"172.19.0.6:47684","extraInfo":{}}}
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.933+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn594","msg":"Connection ended","attr":{"remote":"172.19.0.6:55080","uuid":"20c0ab9b-0a27-4077-be6b-55d6ebf50fff","connectionId":594,"connectionCount":45}}
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.935+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.19.0.6:47690","uuid":"d9745d0f-77c8-49a9-a8e3-f56998839d9b","connectionId":627,"connectionCount":46}}
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.939+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn627","msg":"client metadata","attr":{"remote":"172.19.0.6:47690","client":"conn627","doc":{"driver":{"name":"nodejs|Mongoose","version":"5.1.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.153.1-microsoft-standard-WSL2"},"platform":"Node.js v18.17.1, LE (unified)","version":"5.1.0|7.0.2"}}}
2024-07-05 16:06:28 mongo    | {"t":{"$date":"2024-07-05T08:06:28.943+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn627","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"myusername","authenticationDatabase":"admin","remote":"172.19.0.6:47690","extraInfo":{}}}
2024-07-05 16:06:29 mongo    | {"t":{"$date":"2024-07-05T08:06:29.050+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.19.0.6:47706","uuid":"5c7cd273-40f1-48a5-be8a-de95e0043c5e","connectionId":628,"connectionCount":47}}
2024-07-05 16:06:29 mongo    | {"t":{"$date":"2024-07-05T08:06:29.054+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn628","msg":"client metadata","attr":{"remote":"172.19.0.6:47706","client":"conn628","doc":{"driver":{"name":"nodejs|Mongoose","version":"5.1.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.153.1-microsoft-standard-WSL2"},"platform":"Node.js v18.17.1, LE (unified)","version":"5.1.0|7.0.2"}}}`

**预期结果**

是否由于mongo的问题导致？

**相关截图**
<img width="1460" alt="image" src="https://github.com/labring/FastGPT/assets/52523593/993b8c27-e137-4982-b6c4-a8ab8998e320">

**Comment by c121914yu** [comment]
看着是系统权限问题

**Comment by stephenlzc** [comment]
> 看着是系统权限问题

请问我应该在什么方向中进行排查和设置，谢谢！

**Comment by c121914yu** [comment]
> > 看着是系统权限问题
> 
> 请问我应该在什么方向中进行排查和设置，谢谢！

给 volumn 目录权限。
通过命令行或者可视化工具链接数据进行测试。
或者直接 mongo 社区搜索
