### ISSUE TITLE
can not run fastgpt with external mongo db

### ISSUE THREAD

**Issue by samzong** [labring/FastGPT#204]
```bash
^@error-> mongo connect error
生成QA错误: MongooseError: Operation `trainingdatas.findOneAndUpdate()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/app/node_modules/.pnpm/registry.npmmirror.com+mongoose@6.10.0/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:175:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
/app/node_modules/.pnpm/registry.npmmirror.com+mongoose@6.10.0/node_modules/mongoose/lib/query.js:4927
  const castError = new CastError();
                    ^

CastError: Cast to ObjectId failed for value "" (type string) at path "_id" for model "trainingData"
    at model.Query.exec (/app/node_modules/.pnpm/registry.npmmirror.com+mongoose@6.10.0/node_modules/mongoose/lib/query.js:4927:21)
    at Query.then (/app/node_modules/.pnpm/registry.npmmirror.com+mongoose@6.10.0/node_modules/mongoose/lib/query.js:5026:15)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7) {
  messageFormat: undefined,
  stringValue: '""',
  kind: 'ObjectId',
  value: '',
  path: '_id',
  reason: BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
      at new BSONTypeError (/app/node_modules/.pnpm/registry.npmmirror.com+bson@4.7.2/node_modules/bson/lib/error.js:41:28)
      at new ObjectId (/app/node_modules/.pnpm/registry.npmmirror.com+bson@4.7.2/node_modules/bson/lib/objectid.js:67:23)
      at castObjectId (/app/node_modules/.pnpm/registry.npmmirror.com+mongoose@6.10.0/node_modules/mongoose/lib/cast/objectid.js:25:12)
      at ObjectId.cast (/app/node_modules/.pnpm/registry.npmmirror.com+mongoose@6.10.0/node_modules/mongoose/lib/schema/objectid.js:246:12)
      at SchemaType.applySetters (/app/node_modules/.pnpm/registry.npmmirror.com+mongoose@6.10.0/node_modules/mongoose/lib/schematype.js:1201:12)
      at SchemaType._castForQuery (/app/node_modules/.pnpm/registry.npmmirror.com+mongoose@6.10.0/node_modules/mongoose/lib/schematype.js:1648:15)
      at SchemaType.castForQuery (/app/node_modules/.pnpm/registry.npmmirror.com+mongoose@6.10.0/node_modules/mongoose/lib/schematype.js:1636:15)
      at SchemaType.castForQueryWrapper (/app/node_modules/.pnpm/registry.npmmirror.com+mongoose@6.10.0/node_modules/mongoose/lib/schematype.js:1612:20)
      at cast (/app/node_modules/.pnpm/registry.npmmirror.com+mongoose@6.10.0/node_modules/mongoose/lib/cast.js:349:32)
      at Query.cast (/app/node_modules/.pnpm/registry.npmmirror.com+mongoose@6.10.0/node_modules/mongoose/lib/query.js:5357:12),
  valueType: 'string'
}

Node.js v20.5.0
```

**Comment by c121914yu** [comment]
1. check mongodb status
2. check fastgpt database environment
