### ISSUE TITLE
 gpt4o加载图片 - connect ECONNREFUSED [127.0.0.1:3000](http://127.0.0.1:3000/)  

### ISSUE THREAD

**Issue by ltm0203** [labring/FastGPT#2057]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [X] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 公有云版本 Docker 环境  版本：`fastgpt:v4.8.6  docker-compose-milvus.yml `
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

遇到  gpt4o加载图片的时候报错；  connect ECONNREFUSED [127.0.0.1:3000](http://127.0.0.1:3000/)  

![image](https://github.com/user-attachments/assets/1ed40b09-f1c2-4b0b-a8c6-7bb75b9dd2ed)

环境是Docker compose 环境

我在azure的操作台中是ok的；
![b60785d3-9b3d-4847-b2ff-4034aca26723](https://github.com/user-attachments/assets/41aee779-aff7-44b4-8ef5-3bdce1d73577)

这个是容器中的报错信息：
```bash
2024-07-16 16:18:10 {
2024-07-16 16:18:10   message: 'connect ECONNREFUSED [127.0.0.1:3000](http://127.0.0.1:3000/)',
2024-07-16 16:18:10   stack: 'Error: connect ECONNREFUSED [127.0.0.1:3000](http://127.0.0.1:3000/)\n' +
2024-07-16 16:18:10     '    at AxiosError.from (file:///app/node_modules/.pnpm/axios@1.5.1/node_modules/axios/lib/core/AxiosError.js:89:14)\n' +
2024-07-16 16:18:10     '    at RedirectableRequest.handleRequestError (file:///app/node_modules/.pnpm/axios@1.5.1/node_modules/axios/lib/adapters/http.js:593:25)\n' +
2024-07-16 16:18:10     '    at RedirectableRequest.emit (node:events:514:28)\n' +
2024-07-16 16:18:10     '    at eventHandlers.<computed> (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:38:24)\n' +
2024-07-16 16:18:10     '    at ClientRequest.emit (node:events:514:28)\n' +
2024-07-16 16:18:10     '    at Socket.socketErrorListener (node:_http_client:501:9)\n' +
2024-07-16 16:18:10     '    at Socket.emit (node:events:514:28)\n' +
2024-07-16 16:18:10     '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
2024-07-16 16:18:10     '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
2024-07-16 16:18:10     '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)',
2024-07-16 16:18:10   config: {
2024-07-16 16:18:10     headers: Object [AxiosHeaders] {
2024-07-16 16:18:10       Accept: 'application/json, text/plain, */*',
2024-07-16 16:18:10       'Content-Type': undefined,
2024-07-16 16:18:10       'User-Agent': 'axios/1.5.1',
2024-07-16 16:18:10       'Accept-Encoding': 'gzip, compress, deflate, br'
2024-07-16 16:18:10     },
2024-07-16 16:18:10     url: 'http://localhost:3000/api/system/img/66962c82ffb4e026d63d6d98',
2024-07-16 16:18:10     data: undefined
2024-07-16 16:18:10   }
2024-07-16 16:18:10 }
2024-07-16 16:18:10 [Error] 2024-07-16 08:18:10 sse error: connect ECONNREFUSED [127.0.0.1:3000](http://127.0.0.1:3000/)
```

**Comment by lijiajun1997** [comment]
因为post出去的是url吧 gpt没法访问本地地址

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.8.7 支持 localhost docker 部署的视觉模型。
