### ISSUE TITLE
secretOrPrivateKey must have a value when login

### ISSUE THREAD

**Issue by ahululu** [labring/FastGPT#209]
1. Kubernetes deploy
2. container image: ghcr.io/labring/fastgpt:latest
3. kubernetes env: 
          env:
            - name: MONGODB_URI
              value: "mongodb://xx:xx@mongodb:27017/fastgpt"
            - name: PG_URL
              value: "postgresql://xxx:xxxxxxxx@postgres:5432/fastgpt"
            - name: CHAT_API_KEY
              value: "xxxxxxx"
            - name: ROOT_KEY
              value: "xxxxx"
            - name: DEFAULT_ROOT_PSW
              value: "123456"
Q: secretOrPrivateKey must have a value when login

**Comment by ahululu** [comment]
container logs: 
error: 2023-08-22 01:50:03: secretOrPrivateKey must have a value
{
  message: 'secretOrPrivateKey must have a value',
  stack: 'Error: secretOrPrivateKey must have a value\n' +
    '    at module.exports [as sign] (/app/node_modules/.pnpm/registry.npmmirror.com+jsonwebtoken@9.0.0/node_modules/jsonwebtoken/sign.js:105:20)\n' +
    '    at generateToken (/app/.next/server/chunks/77.js:6185:71)\n' +
    '    at handler (/app/.next/server/pages/api/user/account/loginByPassword.js:167:100)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Object.apiResolver (/app/node_modules/.pnpm/registry.npmmirror.com+next@13.1.6_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/api-utils/node.js:372:9)\n' +
    '    at async NextNodeServer.runApi (/app/node_modules/.pnpm/registry.npmmirror.com+next@13.1.6_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/next-server.js:488:9)\n' +
    '    at async Object.fn (/app/node_modules/.pnpm/registry.npmmirror.com+next@13.1.6_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/next-server.js:751:37)\n' +
    '    at async Router.execute (/app/node_modules/.pnpm/registry.npmmirror.com+next@13.1.6_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/router.js:253:36)\n' +
    '    at async NextNodeServer.run (/app/node_modules/.pnpm/registry.npmmirror.com+next@13.1.6_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/base-server.js:384:29)\n' +
    '    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/registry.npmmirror.com+next@13.1.6_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.58.3/node_modules/next/dist/server/base-server.js:322:20)'

**Comment by ahululu** [comment]
已解决，TOKEN_KEY也必须写在环境变量里
