### ISSUE TITLE
FastGPT本地部署后，提问时报错“LLM model response empty”

### ISSUE THREAD

**Issue by ne0ke718** [labring/FastGPT#2245]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.8-fix2

**问题描述, 日志截图**
1、使用docker部署的，截止2024.8.2部署的最新版本。
2、接入的大模型为本地微调后的Qwen1.5-32B-Chat。采用的通过API的形式部署的。
3、在One API上配置后，测试模型接入正确。如下图：
配置信息为：
![image](https://github.com/user-attachments/assets/1b52bc39-270c-4ffe-8f2d-6aa1b5e0f869)
测试正常
![image](https://github.com/user-attachments/assets/9b5f1228-edbc-4bf4-aa54-693353e4767e)
4、config.json上修改了相关配置信息如下：
![image](https://github.com/user-attachments/assets/0aad5061-3e66-4235-a880-46db784c0898)
![image](https://github.com/user-attachments/assets/18ad260b-56bf-405c-a25b-81f0ce9d0f12)
5、创建与大模型的对话后，提问时 报错信息如下：
![image](https://github.com/user-attachments/assets/94149b83-5b96-4818-9f32-6fdab203771b)
通过"docker logs fastgpt"命令查看log信息如下：
![image](https://github.com/user-attachments/assets/4d26dbd8-4209-4ca5-9bca-d835439de965)
在大模型的接口看到的调试日志，如下，看着是正常的。
![image](https://github.com/user-attachments/assets/b936759b-85e6-465c-962d-77bf11eee47c)
而且通过python正常调用时，输出的日志信息也是这样的。
目前可以确认，本地大模型是没问题的，因为我也接入了MaxKB测试都是正常的。
我同时试了下 在线版的通义千问，是可以正常对话的。

本地大模型对话时，通过抓包看，本地大模型是有响应的，如下图：
<img width="1308" alt="image" src="https://github.com/user-attachments/assets/5e69df91-7351-460d-97e3-7446a6553170">

感谢FastGPT的作者们。帮我看下是哪里的问题。

**Comment by ne0ke718** [comment]
curl 调试，stream为true就返回为空，这个问题怎么解？

**Comment by c121914yu** [comment]
直接看 oneapi 日志

**Comment by mingmars** [comment]
我本地跑ollama3.1也正常，接入oneapi就失败了：oneapi 日志：2024-08-05 00:50:30 [SYS] 2024/08/04 - 16:50:30 | error unmarshalling stream response: invalid character '}' after top-level value 
2024-08-05 00:50:30 [GIN] 2024/08/04 - 16:50:30 | 2024080416502957767324719753944 | 200 |  1.018257115s |      172.18.0.1 |    POST /v1/chat/completions
2024-08-05 00:50:30 [INFO] 2024/08/04 - 16:50:30 | 2024080416502957767324719753944 | record consume log: userId=1, channelId=2, promptTokens=0, completionTokens=0, modelName=llamazk:latest, tokenName=zikao-ollama, quota=0, content=模型倍率 0.15，分组倍率 1.00，补全倍率 2.00 
2024-08-05 00:50:31 [INFO] 2024/08/04 - 16:50:31 | 2024080416503147604390479314346 | user 1 has enough quota 499999996130101, trusted and no need to pre-consume 
2024-08-05 00:50:31 [SYS] 2024/08/04 - 16:50:31 | error unmarshalling stream response: invalid character '}' after top-level value

**Comment by mingmars** [comment]
`我本地跑ollama3.1也正常，通过python调用oneapi正常返回：import openai

# 设置您的 API 密钥
openai.api_key = "sk-topDk54OF8H9hR2I41211dA232144d6e8a4a682f6c6e6201"

# 设置自定义的 API 请求地址
openai.api_base = "http://10.168.1.133:3001/v1"

# 设置对话的 prompt
messages = [
    {"role": "system", "content": ""},
    {"role": "user", "content": "你是谁"}
]
# 使用 OpenAI API 进行聊天
response = openai.ChatCompletion.create(
    model="llamazk:latest",
    messages=messages,
    max_tokens=100,
    n=1,
    stop=None,
    temperature=0.5,
)

# 输出回复
assistant_message = response.choices[0].message
print(assistant_message.content)

，` 但用fastgpt接入oneapi就失败了：oneapi 日志：2024-08-05 00:50:30 [SYS] 2024/08/04 - 16:50:30 | error unmarshalling stream response: invalid character '}' after top-level value
2024-08-05 00:50:30 [GIN] 2024/08/04 - 16:50:30 | 2024080416502957767324719753944 | 200 | 1.018257115s | 172.18.0.1 | POST /v1/chat/completions
2024-08-05 00:50:30 [INFO] 2024/08/04 - 16:50:30 | 2024080416502957767324719753944 | record consume log: userId=1, channelId=2, promptTokens=0, completionTokens=0, modelName=llamazk:latest, tokenName=zikao-ollama, quota=0, content=模型倍率 0.15，分组倍率 1.00，补全倍率 2.00
2024-08-05 00:50:31 [INFO] 2024/08/04 - 16:50:31 | 2024080416503147604390479314346 | user 1 has enough quota 499999996130101, trusted and no need to pre-consume
2024-08-05 00:50:31 [SYS] 2024/08/04 - 16:50:31 | error unmarshalling stream response: invalid character '}' after top-level value

**Comment by mingmars** [comment]
2024-08-05 00:42:54 [Warn] 2024-08-04 16:42:54 LLM response error {"requestBody":{"model":"llamazk:latest","temperature":0.36,"max_tokens":2000,"stream":true,"messages":[{"role":"system","content":"回答要用中文，要有语义符号分断！"},{"role":"user","content":"你是谁"}]}}
2024-08-05 00:42:54 [Error] 2024-08-04 16:42:54 sse error: LLM model response empty
2024-08-05 00:41:55 {
2024-08-05 00:41:55 message: 'LLM model response empty',
2024-08-05 00:41:55 stack: 'Error: LLM model response empty\n' +
2024-08-05 00:41:55 ' at /app/projects/app/.next/server/chunks/96960.js:318:790\n' +
2024-08-05 00:41:55 ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-08-05 00:41:55 ' at async Object.q [as chatNode] (/app/projects/app/.next/server/chunks/96960.js:318:645)\n' +
2024-08-05 00:41:55 ' at async k (/app/projects/app/.next/server/chunks/96960.js:319:2662)\n' +
2024-08-05 00:41:55 ' at async Promise.all (index 0)\n' +
2024-08-05 00:41:55 ' at async C (/app/projects/app/.next/server/chunks/96960.js:319:3248)\n' +
2024-08-05 00:41:55 ' at async v (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:7066)\n' +
2024-08-05 00:41:55 ' at async /app/projects/app/.next/server/pages/api/core/app/detail.js:1:5511\n' +
2024-08-05 00:41:55 ' at async K (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)\n' +
2024-08-05 00:41:55 ' at async U.render (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)'
2024-08-05 00:41:55 }
2024-08-05 00:42:54 {
2024-08-05 00:42:54 message: 'LLM model response empty',
2024-08-05 00:42:54 stack: 'Error: LLM model response empty\n' +
2024-08-05 00:42:54 ' at /app/projects/app/.next/server/chunks/96960.js:318:790\n' +
2024-08-05 00:42:54 ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-08-05 00:42:54 ' at async Object.q [as chatNode] (/app/projects/app/.next/server/chunks/96960.js:318:645)\n' +
2024-08-05 00:42:54 ' at async k (/app/projects/app/.next/server/chunks/96960.js:319:2662)\n' +
2024-08-05 00:42:54 ' at async Promise.all (index 0)\n' +
2024-08-05 00:42:54 ' at async C (/app/projects/app/.next/server/chunks/96960.js:319:3248)\n' +
2024-08-05 00:42:54 ' at async v (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:7066)\n' +
2024-08-05 00:42:54 ' at async /app/projects/app/.next/server/pages/api/core/app/detail.js:1:5511\n' +
2024-08-05 00:42:54 ' at async K (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)\n' +
2024-08-05 00:42:54 ' at async U.render (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)'
2024-08-05 00:42:54 }
2024-08-05 00:43:52 {
2024-08-05 00:43:52 message: 'LLM model response empty',
2024-08-05 00:43:52 stack: 'Error: LLM model response empty\n' +
2024-08-05 00:43:52 ' at /app/projects/app/.next/server/chunks/96960.js:318:790\n' +
2024-08-05 00:43:52 ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-08-05 00:43:52 ' at async Object.q [as chatNode] (/app/projects/app/.next/server/chunks/96960.js:318:645)\n' +
2024-08-05 00:43:52 ' at async k (/app/projects/app/.next/server/chunks/96960.js:319:2662)\n' +
2024-08-05 00:43:52 ' at async Promise.all (index 0)\n' +
2024-08-05 00:43:52 ' at async C (/app/projects/app/.next/server/chunks/96960.js:319:3248)\n' +
2024-08-05 00:43:52 ' at async v (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:7066)\n' +
2024-08-05 00:43:52 ' at async /app/projects/app/.next/server/pages/api/core/app/detail.js:1:5511\n' +
2024-08-05 00:43:52 ' at async K (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)\n' +
2024-08-05 00:43:52 ' at async U.render (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)'
2024-08-05 00:43:52 }
2024-08-05 00:45:00 {
2024-08-05 00:45:00 message: 'LLM model response empty',
2024-08-05 00:45:00 stack: 'Error: LLM model response empty\n' +
2024-08-05 00:45:00 ' at /app/projects/app/.next/server/chunks/96960.js:318:790\n' +
2024-08-05 00:45:00 ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-08-05 00:45:00 ' at async Object.q [as chatNode] (/app/projects/app/.next/server/chunks/96960.js:318:645)\n' +
2024-08-05 00:45:00 ' at async k (/app/projects/app/.next/server/chunks/96960.js:319:2662)\n' +
2024-08-05 00:45:00 ' at async Promise.all (index 0)\n' +
2024-08-05 00:45:00 ' at async C (/app/projects/app/.next/server/chunks/96960.js:319:3248)\n' +
2024-08-05 00:45:00 ' at async J (/app/projects/app/.next/server/pages/api/v1/chat/completions.js:63:12278)\n' +
2024-08-05 00:45:00 ' at async /app/projects/app/.next/server/pages/api/core/app/detail.js:1:5511\n' +
2024-08-05 00:45:00 ' at async K (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)\n' +
2024-08-05 00:45:00 ' at async U.render (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)'
2024-08-05 00:45:00 }
2024-08-05 00:45:36 {
2024-08-05 00:45:36 message: 'LLM model response empty',
2024-08-05 00:45:36 stack: 'Error: LLM model response empty\n' +
2024-08-05 00:45:36 ' at /app/projects/app/.next/server/chunks/96960.js:318:790\n' +
2024-08-05 00:45:36 ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-08-05 00:45:36 ' at async Object.q [as chatNode] (/app/projects/app/.next/server/chunks/96960.js:318:645)\n' +
2024-08-05 00:45:36 ' at async k (/app/projects/app/.next/server/chunks/96960.js:319:2662)\n' +
2024-08-05 00:45:36 ' at async Promise.all (index 0)\n' +
2024-08-05 00:45:36 ' at async C (/app/projects/app/.next/server/chunks/96960.js:319:3248)\n' +
2024-08-05 00:45:36 ' at async J (/app/projects/app/.next/server/pages/api/v1/chat/completions.js:63:12278)\n' +
2024-08-05 00:45:36 ' at async /app/projects/app/.next/server/pages/api/core/app/detail.js:1:5511\n' +
2024-08-05 00:45:36 ' at async K (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)\n' +
2024-08-05 00:45:36 ' at async U.render (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)'
2024-08-05 00:45:36 }
2024-08-05 00:50:30 {
2024-08-05 00:50:30 message: 'LLM model response empty',
2024-08-05 00:50:30 stack: 'Error: LLM model response empty\n' +
2024-08-05 00:50:30 ' at /app/projects/app/.next/server/chunks/96960.js:318:790\n' +
2024-08-05 00:50:30 ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-08-05 00:50:30 ' at async Object.q [as chatNode] (/app/projects/app/.next/server/chunks/96960.js:318:645)\n' +
2024-08-05 00:50:30 ' at async k (/app/projects/app/.next/server/chunks/96960.js:319:2662)\n' +
2024-08-05 00:50:30 ' at async Promise.all (index 0)\n' +
2024-08-05 00:50:30 ' at async C (/app/projects/app/.next/server/chunks/96960.js:319:3248)\n' +
2024-08-05 00:50:30 ' at async J (/app/projects/app/.next/server/pages/api/v1/chat/completions.js:63:12278)\n' +
2024-08-05 00:50:30 ' at async /app/projects/app/.next/server/pages/api/core/app/detail.js:1:5511\n' +
2024-08-05 00:50:30 ' at async K (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)\n' +
2024-08-05 00:50:30 ' at async U.render (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)'
2024-08-05 00:50:30 }
2024-08-05 00:50:34 {
2024-08-05 00:50:34 message: 'LLM model response empty',
2024-08-05 00:50:34 stack: 'Error: LLM model response empty\n' +
2024-08-05 00:50:34 ' at /app/projects/app/.next/server/chunks/96960.js:318:790\n' +
2024-08-05 00:50:34 ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-08-05 00:50:34 ' at async Object.q [as chatNode] (/app/projects/app/.next/server/chunks/96960.js:318:645)\n' +
2024-08-05 00:50:34 ' at async k (/app/projects/app/.next/server/chunks/96960.js:319:2662)\n' +
2024-08-05 00:50:34 ' at async Promise.all (index 0)\n' +
2024-08-05 00:50:34 ' at async C (/app/projects/app/.next/server/chunks/96960.js:319:3248)\n' +
2024-08-05 00:50:34 ' at async J (/app/projects/app/.next/server/pages/api/v1/chat/completions.js:63:12278)\n' +
2024-08-05 00:50:34 ' at async /app/projects/app/.next/server/pages/api/core/app/detail.js:1:5511\n' +
2024-08-05 00:50:34 ' at async K (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)\n' +
2024-08-05 00:50:34 ' at async U.render (/app/node_modules/.pnpm/next@[14.2.5_@babel](mailto:14.2.5_@babel)+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)'

oneapi用pyt程序调用正常返回，但用fastgpt就不行

**Comment by ne0ke718** [comment]
补充下，OneAPI的关键日志如下：


`
[SYS] 2024/08/05 - 09:39:25 | One API v0.6.7 started 
[SYS] 2024/08/05 - 09:39:25 | using MySQL as database 

2024/08/05 09:39:25 /build/model/main.go:79
[error] failed to initialize database, got error dial tcp 172.19.0.4:3306: connect: connection refused
[FATAL] 2024/08/05 - 09:39:25 | [dial tcp 172.19.0.4:3306: connect: connection refused] 
[SYS] 2024/08/05 - 09:39:32 | One API v0.6.7 started 
[SYS] 2024/08/05 - 09:39:32 | using MySQL as database 
[SYS] 2024/08/05 - 09:39:32 | database migration started 
[SYS] 2024/08/05 - 09:39:33 | database migrated 
[SYS] 2024/08/05 - 09:39:33 | REDIS_CONN_STRING not set, Redis is not enabled 
[SYS] 2024/08/05 - 09:39:33 | using theme default 
[SYS] 2024/08/05 - 09:39:33 | memory cache enabled 
[SYS] 2024/08/05 - 09:39:33 | sync frequency: 600 seconds 
[SYS] 2024/08/05 - 09:39:33 | channels synced from database 
[SYS] 2024/08/05 - 09:39:33 | batch update enabled with interval 10s 
[SYS] 2024/08/05 - 09:39:33 | initializing token encoders 
[SYS] 2024/08/05 - 09:39:43 | batch update started 
[SYS] 2024/08/05 - 09:39:43 | batch update finished 
[SYS] 2024/08/05 - 09:39:48 | token encoders initialized 
[SYS] 2024/08/05 - 09:39:48 | server started on http://localhost:3000 
[SYS] 2024/08/05 - 09:42:09 | One API v0.6.7 started 
[SYS] 2024/08/05 - 09:42:09 | using MySQL as database 
[SYS] 2024/08/05 - 09:42:09 | database migration started 
[SYS] 2024/08/05 - 09:42:09 | database migrated 
[SYS] 2024/08/05 - 09:42:09 | REDIS_CONN_STRING not set, Redis is not enabled 
[SYS] 2024/08/05 - 09:42:09 | using theme default 
[SYS] 2024/08/05 - 09:42:09 | memory cache enabled 
[SYS] 2024/08/05 - 09:42:09 | sync frequency: 600 seconds 
[SYS] 2024/08/05 - 09:42:09 | channels synced from database 
[SYS] 2024/08/05 - 09:42:09 | batch update enabled with interval 10s 
[SYS] 2024/08/05 - 09:42:09 | initializing token encoders 
[SYS] 2024/08/05 - 09:42:10 | token encoders initialized 
[SYS] 2024/08/05 - 09:42:10 | server started on http://localhost:3000 
[SYS] 2024/08/05 - 09:42:19 | batch update started 
[SYS] 2024/08/05 - 09:42:19 | batch update finished 
[SYS] 2024/08/05 - 09:42:29 | batch update started 
[SYS] 2024/08/05 - 09:42:29 | batch update finished 
[GIN] 2024/08/05 - 09:42:30 | 2024080509423071593531719330060 | 200 |     752.297µs |  192.168.32.146 |     GET /
[GIN] 2024/08/05 - 09:42:30 | 2024080509423075650864635788410 | 200 |   38.943354ms |  192.168.32.146 |     GET /static/js/main.6bc79654.js
[GIN] 2024/08/05 - 09:42:30 | 2024080509423084498631946627591 | 200 |   37.345507ms |  192.168.32.146 |     GET /static/js/main.6bc79654.js
[GIN] 2024/08/05 - 09:42:30 | 2024080509423095330980224968974 | 200 |     494.952µs |  192.168.32.146 |     GET /api/status
[GIN] 2024/08/05 - 09:42:30 | 2024080509423097422137585823636 | 200 |      462.39µs |  192.168.32.146 |     GET /api/notice
[GIN] 2024/08/05 - 09:42:30 | 2024080509423097555286783202995 | 200 |     204.979µs |  192.168.32.146 |     GET /api/home_page_content
[GIN] 2024/08/05 - 09:42:31 | 2024080509423153594240276143706 | 200 |     637.723µs |  192.168.32.146 |     GET /static/js/832.ab3d9d10.chunk.js
[GIN] 2024/08/05 - 09:42:32 | 2024080509423284444805337121343 | 200 |    1.156232ms |  192.168.32.146 |     GET /api/models
[GIN] 2024/08/05 - 09:42:32 | 2024080509423284425339958975696 | 200 |     2.06197ms |  192.168.32.146 |     GET /api/channel/?p=0
[SYS] 2024/08/05 - 09:42:34 | {"messages":[{"role":"user","content":"hi"}],"model":"qwen1half-32b-chat","max_tokens":2} 
[SYS] 2024/08/05 - 09:42:34 | testing channel #1, response: 
{"model":"qwen1half-32b-chat","choices":[{"index":0,"message":{"role":"assistant","content":"Hello!","tool_calls":null},"finish_reason":"length"}],"usage":{"prompt_tokens":20,"completion_tokens":2,"total_tokens":22},"id":"chatcmpl-4583253881b146ac84865475870c3ff8","object":"chat.completion","created":1722850954} 
[GIN] 2024/08/05 - 09:42:34 | 2024080509423469866591540202254 | 200 |  122.582905ms |  192.168.32.146 |     GET /api/channel/test/1


[SYS] 2024/08/05 - 09:45:02 | model ratio not found: qwen1half-32b-chat 
[INFO] 2024/08/05 - 09:45:02 | 2024080509450263564576849826040 | user 1 has enough quota 499999999972737, trusted and no need to pre-consume 
[GIN] 2024/08/05 - 09:45:03 | 2024080509450263564576849826040 | 200 |  400.659051ms |      172.19.0.9 |    POST /v1/chat/completions
[INFO] 2024/08/05 - 09:45:03 | 2024080509450263564576849826040 | record consume log: userId=1, channelId=1, promptTokens=9, completionTokens=0, modelName=qwen1half-32b-chat, tokenName=Initial Root Token, quota=270, content=模型倍率 30.00，分组倍率 1.00，补全倍率 1.00 
`

可以看到，在OneAPI上进行模型测试的日志，本地模型是正常响应的。下面是通过fastgpt进行调用时OneAPI的输出。

**Comment by ne0ke718** [comment]
关闭吧。我通过xinference发布本地微调后的模型，走xinference的api，解了这个问题。

**Comment by NoComments** [comment]
同样的问题，连接本地模型会提示 LLM model respose empty

**Comment by jhsvip** [comment]
一样的问题 接入deepseek  llm3.2 都是返回为空，用其他工具连接正常

**Comment by hotwa** [comment]
同样的问题，连接本地模型会提示 LLM model respose empty
