### ISSUE TITLE
ghcr.io/labring/fastgpt:v4.8.9-test本地模型已经返回数据但报错：LLM model response empty

### ISSUE THREAD

**Issue by mingmars** [labring/FastGPT#2285]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
  fastgpt:
    container_name: fastgpt
    image: ghcr.io/labring/fastgpt:v4.8.9-test
    ports:
      - 3000:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - pg
      - sandbox
    restart: always
    environment:
      # root 密码，用户名为: root。如果需要修改 root 密码，直接修改这个环境变量，并重启即可。
      - DEFAULT_ROOT_PSW=123456
      # AI模型的API地址哦。务必加 /v1。这里默认填写了OneApi的访问地址。
      - OPENAI_BASE_URL=http://10.168.1.133:3001/v1
      # AI模型的API Key。（这里默认填写了OneAPI的快速默认key，测试通后，务必及时修改）
      - CHAT_API_KEY=sk-YmgyrLgpHRFn2IEq456c002a7fC844429474A612Da050380
      # 数据库最大连接数
      - DB_MAX_LINK=30
      # 登录凭证密钥
      - TOKEN_KEY=any
      # root的密钥，常用于升级时候的初始化请求
      - ROOT_KEY=root_key
      # 文件阅读加密
      - FILE_TOKEN_KEY=filetoken
      # MongoDB 连接参数. 用户名myusername,密码mypassword。
      - MONGODB_URI=mongodb://myusername:mypassword@mongo:27017/fastgpt?authSource=admin
      # pg 连接参数
      - PG_URL=postgresql://username:password@pg:5432/postgres
      # sandbox 地址
      - SANDBOX_URL=http://sandbox:3000
      # 日志等级: debug, info, warn, error
      - LOG_LEVEL=info
    volumes:
      - ./config.json:/app/data/config.json

2024-08-07 01:05:05             from modeldata 
2024-08-07 01:05:05             where team_id='66adfdf1604527968b7361e2'
2024-08-07 01:05:05               AND dataset_id IN ('66ae7a87d229f5a483c5b695')
2024-08-07 01:05:05               
2024-08-07 01:05:05               
2024-08-07 01:05:05             order by score limit 100;
2024-08-07 01:05:05         COMMIT; 
2024-08-07 01:05:06 [Warn] 2024-08-06 17:05:06 LLM response error {"requestBody":{"model":"llamazk:latest","temperature":0.36,"max_tokens":1950,"stream":true,"messages":[{"role":"user","content":"使用 <Data></Data> 标记中的内容作为你的知识:\n\n<Data>\n\n</Data>\n\n回答要求：\n- 如果你不清楚答案，你需要澄清。\n- 避免提及你是从 <Data></Data> 获取的知识。\n- 保持答案与 <Data></Data> 中描述的一致。\n- 使用 Markdown 语法优化回答格式。\n- 使用与问题相同的语言回答。\n\n问题:\"\"\"如何使用\"\"\""}]}}
2024-08-07 01:05:06 [Error] 2024-08-06 17:05:06 sse error: LLM model response empty 
2024-08-07 01:05:06 {
2024-08-07 01:05:06   message: 'LLM model response empty',
2024-08-07 01:05:06   stack: 'Error: LLM model response empty\n' +
2024-08-07 01:05:06     '    at /app/projects/app/.next/server/chunks/96960.js:329:668\n' +
2024-08-07 01:05:06     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-08-07 01:05:06     '    at async Object.q [as chatNode] (/app/projects/app/.next/server/chunks/96960.js:329:523)\n' +
2024-08-07 01:05:06     '    at async k (/app/projects/app/.next/server/chunks/96960.js:330:2698)\n' +
2024-08-07 01:05:06     '    at async Promise.all (index 0)\n' +
2024-08-07 01:05:06     '    at async B (/app/projects/app/.next/server/chunks/96960.js:330:3284)\n' +
2024-08-07 01:05:06     '    at async v (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:7081)\n' +
2024-08-07 01:05:06     '    at async /app/projects/app/.next/server/pages/api/support/user/account/tokenLogin.js:1:5544\n' +
2024-08-07 01:05:06     '    at async K (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)\n' +
2024-08-07 01:05:06     '    at async U.render (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)'
2024-08-07 01:05:06 }
2024-08-07 01:05:06 [Warn] 2024-08-06 17:05:06 Request finish /api/core/chat/chatTest, time: 7966ms

- [ ] 公有云版本
- [ ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
未返回任何内容，自行按文档检查

**Comment by sdytzjp** [comment]
我发现有时候如果给大模型输入的内容太多也报这个错误
