### ISSUE TITLE
对接自己部署的Embedding  生成向量错误

### ISSUE THREAD

**Issue by lifeofbow** [labring/FastGPT#230]
init pg successful
2023-08-28 09:41:01 【QA】任务完成
2023-08-28 09:41:01 生成向量错误: RangeError: Invalid array length
2023-08-28 09:41:01     at unityDimensional (/app/.next/server/chunks/5686.js:3680:24)
2023-08-28 09:41:01     at /app/.next/server/chunks/5686.js:3667:48
2023-08-28 09:41:01     at Array.map (<anonymous>)
2023-08-28 09:41:01     at /app/.next/server/chunks/5686.js:3667:36
2023-08-28 09:41:01     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-28 09:41:01     at async getVector (/app/.next/server/chunks/5686.js:3654:20)
2023-08-28 09:41:01     at async generateVector (/app/.next/server/chunks/5686.js:4329:30)
2023-08-28 09:41:02 【索引】任务完成

**Comment by c121914yu** [comment]
向量维度超过1536了，不支持超过1536维度的向量
