### ISSUE TITLE
docker 后台的log总是出现 `SyntaxError: Unexpected token`

### ISSUE THREAD

**Issue by LiSiruiRay** [labring/FastGPT#2426]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 3.3

**问题描述, 日志截图**
docker 后台的log总是出现 `SyntaxError: Unexpected token`
完整报错：

```2024-08-18 15:46:56 fastgpt  | SyntaxError: Unexpected token '根', "根据提供的历史记录和"... is not valid JSON
2024-08-18 15:46:56 fastgpt  |     at JSON.parse (<anonymous>)
2024-08-18 15:46:56 fastgpt  |     at d (/app/projects/app/.next/server/chunks/96960.js:268:435)
2024-08-18 15:46:56 fastgpt  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-08-18 15:46:56 fastgpt  |     at async /app/projects/app/.next/server/chunks/96960.js:271:253
2024-08-18 15:46:56 fastgpt  |     at async l (/app/projects/app/.next/server/chunks/96960.js:271:214)
2024-08-18 15:46:56 fastgpt  |     at async Object.y [as datasetSearchNode] (/app/projects/app/.next/server/chunks/96960.js:336:4126)
2024-08-18 15:46:56 fastgpt  |     at async k (/app/projects/app/.next/server/chunks/96960.js:337:2698)
2024-08-18 15:46:56 fastgpt  |     at async Promise.all (index 0)
2024-08-18 15:46:56 fastgpt  |     at async B (/app/projects/app/.next/server/chunks/96960.js:337:3284)
2024-08-18 15:46:56 fastgpt  |     at async v (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:7081)
```

**复现步骤**

**预期结果**

**相关截图**
<img width="639" alt="Screenshot 2024-08-18 at 8 02 49 PM" src="https://github.com/user-attachments/assets/cb0a9bf7-a220-40cf-ae00-066708fc6d24">

还有一个伴随的问题是我的知识库总是卡在索引，我用的m3e，但是我不确定是不是因为我电脑配置不够，我用的M1 pro 16GB RAM，测过m3e跑过了，测试的script用了5分钟才生成出embedding，后来我改成了openai的embedding就没问题了

**Comment by c121914yu** [comment]
你提供的日志提示和你的错误没有任何关系

**Comment by c121914yu** [comment]
你提供的日志提示和你的错误没有任何关系。
第一个错误是读 pdf 文件错误，不影响任何东西。
第二个是模型没按要求生成 json 内容导致的。

**Comment by LiSiruiRay** [comment]
> 你提供的日志提示和你的错误没有任何关系。 第一个错误是读 pdf 文件错误，不影响任何东西。 第二个是模型没按要求生成 json 内容导致的。

好的谢谢！那第二个如果出现这种情况的话会有什么影响吗？是只会让模型重新生成一遍吗？谢谢谢谢！
