### ISSUE TITLE
期望文件上传功能支持的文档类型中增加对office早期类型(xsl、doc、ppt)的支持

### ISSUE THREAD

**Issue by JiesenSun** [labring/FastGPT#2507]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 features
- [x] 我已确认我已升级到最新版本
- [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
感谢官方在4.8.9版本中支持了对于呼声很高的文件上传功能，实际使用中，发现对office早期类型（xls、doc、ppt）是不支持的，
期望能够兼容早期类型。
`export const documentFileType = '.txt, .docx, .csv, .xlsx, .pdf, .md, .html, .pptx';`

**应用场景**
目前在我们应用场景中，有许多早期的office文档类型需要处理

**相关示例**

**Comment by sdytzjp** [comment]
知识库的附件也建议增加

**Comment by liuquanqing** [comment]
可能只是前端对后缀做了拦截，一般处理都是支持的

**Comment by SDAIer** [comment]
> 可能只是前端对后缀做了拦截，一般处理都是支持的

通过API接口测试了下不支持。
文档解析如下
File: Only support .txt, .md, .html, .pdf, .docx, pptx, .csv, .xlsx

**Comment by SDAIer** [comment]
我通过python将doc、xls、ppt转换格式为docx xlsx pptx。通过API来调用AI。
doc和xls文件，通过API调用AI然后调用文档解析，都可以正常解析。
但是ppt转换成pptx以后（转换的pptx可以正常打开），fastgpt文档解析模块报错，如下：
```
[xmldom error]  invalid doc source
@#[line:0,col:undefined]
TypeError: Cannot read properties of undefined (reading 'getElementsByTagName')
    at /app/projects/app/.next/server/worker/readFile.js:34:1635
    at Array.forEach (<anonymous>)
    at g (/app/projects/app/.next/server/worker/readFile.js:34:1613)
    at async m (/app/projects/app/.next/server/worker/readFile.js:34:2176)
    at async Object.s (/app/projects/app/.next/server/worker/readFile.js:32:387)
    at async MessagePort.<anonymous> (/app/projects/app/.next/server/worker/readFile.js:34:808)
error => Cannot read properties of undefined (reading 'getElementsByTagName')
```

### python日志如下,成功将doc、xls、ppt转换为docx\xlsx\pptx，而且转换的文件都可以正常打开。
```
172.19.0.5 - - [04/Nov/2024 18:49:11] "POST /process_data1 HTTP/1.1" 200 -
convert /usr/share/nginx/test/测试3.xls -> /usr/share/nginx/test//测试3.xlsx using filter : Calc Office Open XML
172.19.0.5 - - [04/Nov/2024 18:49:16] "POST /process_data1 HTTP/1.1" 200 -
convert /usr/share/nginx/test/123.ppt -> /usr/share/nginx/test//123.pptx using filter : Impress MS PowerPoint 2007 XML
172.19.0.5 - - [04/Nov/2024 18:50:21] "POST /process_data1 HTTP/1.1" 200 -


172.19.0.5 - - [04/Nov/2024 18:54:11] "POST /process_data1 HTTP/1.1" 200 -
convert /usr/share/nginx/test/22.doc -> /usr/share/nginx/test//22.docx using filter : MS Word 2007 XML
172.19.0.5 - - [04/Nov/2024 18:54:59] "POST /process_data1 HTTP/1.1" 200 -
```
