### ISSUE TITLE
猜你想问接口 /api/core/ai/agent/createQuestionGuide 报500错误

### ISSUE THREAD

**Issue by Jie2GG** [labring/FastGPT#2653]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: v4.8.10-fix

**问题描述, 日志截图**
在简单应用打开猜你想问功能后，问答不生效。
HTTP响应：
<img width="439" alt="image" src="https://github.com/user-attachments/assets/5a3774e7-9899-4671-a7cd-f0c12b7d38dd">
返回内容
```text
{
    "code": 500,
    "statusText": "",
    "message": "bad response status code 400 (request id: 2024090909143933861328236420945)",
    "data": null
}
```

fastGPT日志：
```text
[Info] 2024-09-09 09:14:22 finish completions {"source":"fastgpt","teamId":"66d90b95f024b4727ad0e712","totalPoints":0}
[Warn] 2024-09-09 09:14:22 Request finish /api/core/chat/chatTest, time: 16460ms 
Warning: data for page "/app/detail" (path "/app/detail?appId=66d9167ff024b4727ad1d65e&currentTab=publish") is 167 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
See more info here: https://nextjs.org/docs/messages/large-page-data
[Error] 2024-09-09 09:14:39 Api response error: undefined, bad response status code 400 (request id: 2024090909143933861328236420945) 
{
  message: '400 bad response status code 400 (request id: 2024090909143933861328236420945)',
  stack: 'Error: 400 bad response status code 400 (request id: 2024090909143933861328236420945)\n' +
    '    at tQ.generate (/app/projects/app/.next/server/chunks/61638.js:19:87222)\n' +
    '    at rd.makeStatusError (/app/projects/app/.next/server/chunks/61638.js:19:78991)\n' +
    '    at rd.makeRequest (/app/projects/app/.next/server/chunks/61638.js:19:79914)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async u (/app/projects/app/.next/server/pages/api/core/ai/agent/createQuestionGuide.js:1:2652)\n' +
    '    at async p (/app/projects/app/.next/server/pages/api/core/ai/agent/createQuestionGuide.js:1:5652)\n' +
    '    at async K (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)\n' +
    '    at async U.render (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)\n' +
    '    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/next-server.js:600:9)\n' +
    '    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/next-server.js:269:37)'
}
```
**复现步骤**
1. 创建简单应用
2. 选择模型（使用的是本地 xinference 部署的 qwen2-72b-instruct-awq）
3. 向模型提问

**预期结果**
猜你想问功能正常

**相关截图**
简单应用配置：
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/914e1dd4-a3fd-431c-86e2-1c8bc6e43b89">

OneAPI配置：
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/965d79db-6767-40d4-ba78-4f1fd738f62d">

Xinference配置：
<img width="908" alt="image" src="https://github.com/user-attachments/assets/ff4bfadf-2139-40fd-b7be-343eee852980">

**Comment by c121914yu** [comment]
调用模型报错，自行检查模型

**Comment by c121914yu** [comment]
可以直接看源码里的请求来模拟，就一小段提示词

**Comment by Jie2GG** [comment]
> 可以直接看源码里的请求来模拟，就一小段提示词

直接请求 vllm 后端么？

**Comment by c121914yu** [comment]
> > 可以直接看源码里的请求来模拟，就一小段提示词
> 
> 直接请求 vllm 后端么？

先测 oneapi 再 vllm

**Comment by Jie2GG** [comment]
@c121914yu 
没有学过 ts，目前检索到的猜你想问的内容只有这些，这个是 prompt 是这个吗？

<img width="429" alt="image" src="https://github.com/user-attachments/assets/561c605e-d114-447c-8bcf-f86593fbe032">

**Comment by Jie2GG** [comment]
@c121914yu 
我找到了 prompt，并且尝试构造了一个请求，OneAPI端有正常返回信息
<img width="1587" alt="image" src="https://github.com/user-attachments/assets/e0e1e920-859d-41fa-8a23-a4fe12d60f27">
