### ISSUE TITLE
duckduckgo插件报错

### ISSUE THREAD

**Issue by sdytzjp** [labring/FastGPT#2683]
4.8.10-fix

时间插件、网页抓取插件都ok

## 服务器网络
![366767623-958e7f7b-f895-4596-801f-2600f6a85162](https://github.com/user-attachments/assets/67b46774-df17-4c22-ae43-3e93f65d4cc1)

## duckduckgo 搜索报错
Error: Failed to get the VQD for query "google怎么访问".
    at c (/app/projects/app/.next/server/chunks/7160.js:1:19757)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async h (/app/projects/app/.next/server/chunks/7160.js:1:7564)
    at async c (/app/projects/app/.next/server/chunks/61727.js:5:348)
    at async MessagePort.<anonymous> (/app/projects/app/.next/server/worker/systemPluginRun.js:1:285)
[Info] 2024-09-12 07:18:28 Worker systemPluginRun run time: 11116ms
[Info] 2024-09-12 07:18:30 finish completions {"source":"fastgpt","teamId":"667bc3151aad8819f3aced37","totalPoints":0}
[Warn] 2024-09-12 07:18:30 Request finish /api/core/chat/chatTest, time: 14104ms

## 图片搜索，如下
![图片](https://github.com/user-attachments/assets/2db41fd8-0778-4c4e-bd7b-a279ce0815f7)

## 新闻搜索
![图片](https://github.com/user-attachments/assets/4dc8639f-b5a5-4d96-ab05-11ff6314c563)

## 视频搜索
![图片](https://github.com/user-attachments/assets/f798340e-3689-490d-b512-2e8d0d60d64b)

**Comment by sdytzjp** [comment]
![图片](https://github.com/user-attachments/assets/dd07252e-b2c7-4abf-941d-e70b1cba5a12)

**Comment by c121914yu** [comment]
用国外的服务器，用代理没用
