### ISSUE TITLE
登录报错，提示网络异常，无法进入主页面,docker logs fastgpt : message: "JSON5: invalid character '<' at 7:1",

### ISSUE THREAD

**Issue by songlinyang** [labring/FastGPT#2693]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [latest & 4.8.9 & 4.8.8 ] 公有云版本
- [latest & 4.8.9 & 4.8.4] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
Load model====== chatitems
mongo start connect
mongo connected
System Version: 4.8.7
[Error] 2024-09-12 14:33:22 init error 
{
  message: "JSON5: invalid character '<' at 7:1",
  stack: "SyntaxError: JSON5: invalid character '<' at 7:1\n" +
    '    at syntaxError (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:1110:17)\n' +
    '    at invalidChar (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:1055:12)\n' +
    '    at Object.value (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:309:15)\n' +
    '    at lex (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:100:42)\n' +
    '    at Object.parse (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:25:17)\n' +
    '    at h (/app/projects/app/.next/server/chunks/96960.js:324:29374)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async /app/projects/app/.next/server/chunks/96960.js:326:4438'
}
Load model====== system_logs
  ▲ Next.js 14.2.5
  - Local:        http://044f6cd73fd5:3000
  - Network:      http://172.18.0.7:3000

 ✓ Starting...
 ✓ Ready in 405ms
Load model====== openapi
Load model====== resource_permission
Load model====== datasets
Load model====== dataset_collections
Load model====== dataset_trainings
Load model====== team_subscriptions
Load model====== apps
Load model====== dataset_datas
Load model====== image
Load model====== dataset.files
Load model====== buffer_rawtexts
Load model====== systemtimerlocks
Load model====== systemConfigs
Load model====== app_system_plugins
Load model====== users
Load model====== team_members
Load model====== teams
Load model====== chatitems
mongo start connect
mongo connected
System Version: 4.8.7
[Error] 2024-09-12 14:33:26 init error 
{
  message: "JSON5: invalid character '<' at 7:1",
  stack: "SyntaxError: JSON5: invalid character '<' at 7:1\n" +
    '    at syntaxError (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:1110:17)\n' +
    '    at invalidChar (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:1055:12)\n' +
    '    at Object.value (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:309:15)\n' +
    '    at lex (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:100:42)\n' +
    '    at Object.parse (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:25:17)\n' +
    '    at h (/app/projects/app/.next/server/chunks/96960.js:324:29374)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async /app/projects/app/.next/server/chunks/96960.js:326:4438'
}
Load model====== system_logs
  ▲ Next.js 14.2.5
  - Local:        http://044f6cd73fd5:3000
  - Network:      http://172.18.0.7:3000

 ✓ Starting...
 ✓ Ready in 387ms
Load model====== openapi
Load model====== resource_permission
Load model====== datasets
Load model====== dataset_collections
Load model====== dataset_trainings
Load model====== team_subscriptions
Load model====== apps
Load model====== dataset_datas
Load model====== image
Load model====== dataset.files
Load model====== buffer_rawtexts
Load model====== systemtimerlocks
Load model====== systemConfigs
Load model====== app_system_plugins
Load model====== users
Load model====== team_members
Load model====== teams
Load model====== chatitems
mongo start connect
mongo connected
System Version: 4.8.7
[Error] 2024-09-12 14:33:30 init error 
{
  message: "JSON5: invalid character '<' at 7:1",
  stack: "SyntaxError: JSON5: invalid character '<' at 7:1\n" +
    '    at syntaxError (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:1110:17)\n' +
    '    at invalidChar (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:1055:12)\n' +
    '    at Object.value (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:309:15)\n' +
    '    at lex (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:100:42)\n' +
    '    at Object.parse (/app/node_modules/.pnpm/json5@2.2.3/node_modules/json5/lib/parse.js:25:17)\n' +
    '    at h (/app/projects/app/.next/server/chunks/96960.js:324:29374)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async /app/projects/app/.next/server/chunks/96960.js:326:4438'
}
Load model====== system_logs
  ▲ Next.js 14.2.5
  - Local:        http://044f6cd73fd5:3000
  - Network:      http://172.18.0.7:3000

**复现步骤**
登录报错，提示网络异常，无法进入主页面
**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/c1def518-330f-441f-a465-7be64aa95ae2)
![image](https://github.com/user-attachments/assets/c1def518-330f-441f-a465-7be64aa95ae2)
![image](https://github.com/user-attachments/assets/c1def518-330f-441f-a465-7be64aa95ae2)

**Comment by songlinyang** [comment]
不是问题，因加载的config.json内容不是非法的json格式。文档已告知
