### ISSUE TITLE
私有化部署vision模型的时候报错

### ISSUE THREAD

**Issue by USTC-Wentao-Yang** [labring/FastGPT#2730]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**
4.8.10-fix2
- [ ] 公有云版本
- [ ☑️] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
 ○ Compiling /api/common/file/read ...
[Error] 2024-09-18 03:08:13 sse error: Service Unavailable 
{
  message: 'Request failed with status code 503',
  stack: 'AxiosError: Request failed with status code 503\n' +
    '    at settle (file:///workspace/node_modules/.pnpm/axios@1.7.2/node_modules/axios/lib/core/settle.js:19:12)\n' +
    '    at IncomingMessage.handleStreamEnd (file:///workspace/node_modules/.pnpm/axios@1.7.2/node_modules/axios/lib/adapters/http.js:589:11)\n' +
    '    at IncomingMessage.emit (node:events:529:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1400:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n' +
    '    at Axios.request (file:///workspace/node_modules/.pnpm/axios@1.7.2/node_modules/axios/lib/core/Axios.js:45:41)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async eval (webpack-internal:///(api)/../../packages/service/core/chat/utils.ts:142:34)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async parseUserContent (webpack-internal:///(api)/../../packages/service/core/chat/utils.ts:130:24)\n' +
    '    at async eval (webpack-internal:///(api)/../../packages/service/core/chat/utils.ts:222:26)\n' +
    '    at async Promise.all (index 2)\n' +
    '    at async loadRequestMessages (webpack-internal:///(api)/../../packages/service/core/chat/utils.ts:218:26)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Object.dispatchChatCompletion [as chatNode] (webpack-internal:///(api)/../../packages/service/core/workflow/dispatch/chat/oneapi.ts:98:43)\n' +
    '    at async nodeRunWithActive (webpack-internal:///(api)/../../packages/service/core/workflow/dispatch/index.ts:398:29)\n' +
    '    at async checkNodeCanRun (webpack-internal:///(api)/../../packages/service/core/workflow/dispatch/index.ts:289:31)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async checkNodeCanRun (webpack-internal:///(api)/../../packages/service/core/workflow/dispatch/index.ts:321:45)\n' +
    '    at async Promise.all (index 1)',
  config: {
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'axios/1.7.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    url: '/api/common/file/read?filename=截屏2024-09-12 14.20.36.png&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidWNrZXROYW1lIjoiY2hhdCIsInRlYW1JZCI6IjY2ZTRmNGQ5YmJjNjRiYjMyNWI0NjdkMyIsInRtYklkIjoiNjZlNGY0ZDliYmM2NGJiMzI1YjQ2N2Q1IiwiZmlsZUlkIjoiNjZlYTQ0MWI0NzdkMGNkNmYzNGQ1YTQ5IiwiZXhwIjoxNzI3MjMzNjkxLCJpYXQiOjE3MjY2Mjg4OTF9.oVOUVobKQJIVxzBF5_5FgyztJ-2Wpfzx3XUtI5RdPH4',
    data: undefined
  },
  response: { status: 503, statusText: 'Service Unavailable' }
}

**Comment by lijiajun1997** [comment]
是不是api接口和openai接收图片的方式不一样？

**Comment by USTC-Wentao-Yang** [comment]
> 是不是api接口和openai接收图片的方式不一样？

不是，都没到oneapi阶段，已经定位到问题
          const response = await axios.get(imgUrl, {
            baseURL: serverRequestBaseUrl,
            responseType: 'arraybuffer'
          });
