### ISSUE TITLE
求助！！！fastgpt启动登陆页面BUG

### ISSUE THREAD

**Issue by Microslargh** [labring/FastGPT#2841]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ X] 我已确认目前没有类似 issue
- [ X] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [ X] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ X] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [X ] 私有部署版本, 具体版本号: 

**问题描述, 日志截图**
Server Error
Error: Error serializing `.ChineseRedirectUrl` returned from `getServerSideProps` in "/login".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.

 ⨯ N [Error]: Error serializing `.ChineseRedirectUrl` returned from `getServerSideProps` in "/login".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
    at r (/home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:446)
    at /home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:683
    at Array.every (<anonymous>)
    at r (/home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:580)
    at $ (/home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:1100)
    at e8 (/home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:25:1525)
    at async doRender (/home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1425:30)
    at async cacheEntry.responseCache.get.routeKind (/home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1931:24)
    at async DevServer.renderToResponseImpl (/home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1969:32)
    at async DevServer.pipeImpl (/home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:816:17)
    at async /home/simply/XDU/simply/fastgpt/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/dev/next-dev-server.js:339:20 {
  page: '/login'

**复现步骤**

**预期结果**

**相关截图**

**Comment by c121914yu** [comment]
目前没遇到过

**Comment by Microslargh** [comment]
> 目前没遇到过，请提供更多详细信息

![2024-09-30 18-12-13 的屏幕截图](https://github.com/user-attachments/assets/c2aeba7b-77e5-4d9e-b280-955f157be3ff)
情况是我用docker-compose部署的方式可以正常走完全部流程并且实现对话，但是当我想进行本地开发的的时候我安装官方的文档利用make编译出来的fastgpt网页，在加载完侧边的应用按钮后提示我要登陆，但是登陆的login页面显示不出来直接跳出错误。

以下是全部的log信息
pnpm --prefix ./projects/app dev

> app@4.8.10 dev /home/simply/XDU/simply/FastGPT/projects/app
> next dev

  ▲ Next.js 14.2.5
  - Local:        http://localhost:3000
  - Environments: .env.local
  - Experiments (use with caution):
    · outputFileTracingRoot

 ✓ Starting...
 ✓ Ready in 10s
 ○ Compiling / ...
 ✓ Compiled / in 12.4s (6893 modules)
Warning: data for page "/" is 146 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
See more info here: https://nextjs.org/docs/messages/large-page-data
 GET / 200 in 13585ms
 ○ Compiling /app/list ...
 ✓ Compiled /app/list in 11.6s (8583 modules)
Load model====== openapi
Load model====== resource_permission
Load model====== datasets
Load model====== dataset_collections
Load model====== dataset_trainings
Load model====== team_subscriptions
Load model====== apps
Load model====== dataset_datas
Load model====== image
Load model====== dataset.files
Load model====== chat.files
Load model====== buffer_rawtexts
Load model====== dataset_collection_tags
Load model====== systemtimerlocks
Load model====== app_versions
Load model====== chat
Load model====== systemConfigs
Load model====== app_system_plugins
Load model====== users
Load model====== team_members
Load model====== teams
Load model====== chatitems
mongo start connect
mongo connected
System Version: 4.8.10
[Info] 2024-09-30 18:11:39 Load system plugin successfully: 16 
{
  feConfigs: {
    lafEnv: 'https://laf.dev',
    show_emptyChat: true,
    show_git: true,
    docUrl: 'https://doc.tryfastgpt.ai',
    openAPIDocUrl: 'https://doc.tryfastgpt.ai/docs/development/openapi',
    systemPluginCourseUrl: 'https://fael3z0zfze.feishu.cn/wiki/ERZnw9R26iRRG0kXZRec6WL9nwh',
    appTemplateCourse: 'https://fael3z0zfze.feishu.cn/wiki/CX9wwMGyEi5TL6koiLYcg7U0nWb?fromScene=spaceOverview',
    systemTitle: 'FastGPT',
    concatMd: '项目开源地址: [FastGPT GitHub](https://github.com/labring/FastGPT)\n' +
      '交流群: ![](https://oss.laf.run/htr4n1-images/fastgpt-qr-code.jpg)',
    limit: { exportDatasetLimitMinutes: 0, websiteSyncLimitMinuted: 0 },
    scripts: [],
    favicon: '/favicon.ico',
    uploadFileMaxSize: 500,
    isPlus: false
  },
  systemEnv: { vectorMaxProcess: 15, qaMaxProcess: 15, pgHNSWEfSearch: 100 },
  subPlans: undefined,
  llmModels: [
    {
      model: 'gpt-4o-mini',
      name: 'gpt-4o-mini',
      avatar: '/imgs/model/openai.svg',
      maxContext: 125000,
      maxResponse: 16000,
      quoteMaxToken: 120000,
      maxTemperature: 1.2,
      charsPointsPrice: 0,
      censor: false,
      vision: true,
      datasetProcess: true,
      usedInClassify: true,
      usedInExtractFields: true,
      usedInToolCall: true,
      usedInQueryExtension: true,
      toolChoice: true,
      functionCall: false,
      customCQPrompt: '',
      customExtractPrompt: '',
      defaultSystemChatPrompt: '',
      defaultConfig: {},
      fieldMap: {}
    },
    {
      model: 'gpt-4o',
      name: 'gpt-4o',
      avatar: '/imgs/model/openai.svg',
      maxContext: 125000,
      maxResponse: 4000,
      quoteMaxToken: 120000,
      maxTemperature: 1.2,
      charsPointsPrice: 0,
      censor: false,
      vision: true,
      datasetProcess: true,
      usedInClassify: true,
      usedInExtractFields: true,
      usedInToolCall: true,
      usedInQueryExtension: true,
      toolChoice: true,
      functionCall: false,
      customCQPrompt: '',
      customExtractPrompt: '',
      defaultSystemChatPrompt: '',
      defaultConfig: {},
      fieldMap: {}
    },
    {
      model: 'o1-mini',
      name: 'o1-mini',
      avatar: '/imgs/model/openai.svg',
      maxContext: 125000,
      maxResponse: 4000,
      quoteMaxToken: 120000,
      maxTemperature: 1.2,
      charsPointsPrice: 0,
      censor: false,
      vision: false,
      datasetProcess: true,
      usedInClassify: true,
      usedInExtractFields: true,
      usedInToolCall: true,
      usedInQueryExtension: true,
      toolChoice: false,
      functionCall: false,
      customCQPrompt: '',
      customExtractPrompt: '',
      defaultSystemChatPrompt: '',
      defaultConfig: [Object],
      fieldMap: [Object]
    },
    {
      model: 'o1-preview',
      name: 'o1-preview',
      avatar: '/imgs/model/openai.svg',
      maxContext: 125000,
      maxResponse: 4000,
      quoteMaxToken: 120000,
      maxTemperature: 1.2,
      charsPointsPrice: 0,
      censor: false,
      vision: false,
      datasetProcess: true,
      usedInClassify: true,
      usedInExtractFields: true,
      usedInToolCall: true,
      usedInQueryExtension: true,
      toolChoice: false,
      functionCall: false,
      customCQPrompt: '',
      customExtractPrompt: '',
      defaultSystemChatPrompt: '',
      defaultConfig: [Object],
      fieldMap: [Object]
    }
  ],
  vectorModels: [
    {
      model: 'text-embedding-ada-002',
      name: 'Embedding-2',
      avatar: '/imgs/model/openai.svg',
      charsPointsPrice: 0,
      defaultToken: 700,
      maxToken: 3000,
      weight: 100,
      defaultConfig: {},
      dbConfig: {},
      queryConfig: {}
    },
    {
      model: 'text-embedding-3-large',
      name: 'text-embedding-3-large',
      avatar: '/imgs/model/openai.svg',
      charsPointsPrice: 0,
      defaultToken: 512,
      maxToken: 3000,
      weight: 100,
      defaultConfig: [Object]
    },
    {
      model: 'text-embedding-3-small',
      name: 'text-embedding-3-small',
      avatar: '/imgs/model/openai.svg',
      charsPointsPrice: 0,
      defaultToken: 512,
      maxToken: 3000,
      weight: 100
    }
  ],
  reRankModels: [],
  audioSpeechModels: [
    {
      model: 'tts-1',
      name: 'OpenAI TTS1',
      charsPointsPrice: 0,
      voices: [Array]
    }
  ],
  whisperModel: { model: 'whisper-1', name: 'Whisper1', charsPointsPrice: 0 }
}
pg connected
default team exist new ObjectId("66fa3b7b69904557eb2be676")
root user init: { username: 'root', password: '123456' }
[Info] 2024-09-30 18:11:40 init pg successful 
 GET /api/common/system/getInitData 304 in 13047ms
[Info] 2024-09-30 18:11:40 [Vector Queue] Done 
[Info] 2024-09-30 18:11:40 [QA Queue] Done 
 GET /_next/data/development/zh/app/list.json 200 in 289ms
 ○ Compiling /api/support/user/account/tokenLogin ...
 ✓ Compiled /api/support/user/account/tokenLogin in 10.6s (3140 modules)
 ✓ Compiled (3143 modules)
[Debug] 2024-09-30 18:11:51 Request start /api/support/user/team/plan/getTeamPlanStatus?maxQuantity=1 
[Debug] 2024-09-30 18:11:51 Request start /api/support/user/account/tokenLogin 
 GET /api/support/user/team/plan/getTeamPlanStatus?maxQuantity=1 304 in 11379ms
 GET /api/support/user/account/tokenLogin 304 in 11375ms
 ○ Compiling /api/support/user/account/loginout ...
 ✓ Compiled /api/support/user/account/loginout in 5.2s (8897 modules)
 GET /api/support/user/account/loginout 304 in 5292ms
 GET /api/support/user/account/loginout 304 in 137ms
 ⨯ N [Error]: Error serializing `.ChineseRedirectUrl` returned from `getServerSideProps` in "/login".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
    at r (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:446)
    at /home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:683
    at Array.every (<anonymous>)
    at r (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:580)
    at $ (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:1100)
    at e8 (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:25:1525)
    at async doRender (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1425:30)
    at async cacheEntry.responseCache.get.routeKind (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1931:24)
    at async DevServer.renderToResponseImpl (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1969:32)
    at async DevServer.pipeImpl (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:816:17)
    at async /home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/dev/next-dev-server.js:339:20 {
  page: '/login'
}
 ○ Compiling /_error ...
 ✓ Compiled /_error in 2.3s (8897 modules)
Warning: data for page "/_error" (path "/login?lastRoute=%2Fapp%2Flist") is 150 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
See more info here: https://nextjs.org/docs/messages/large-page-data
 GET /_next/data/development/zh/login.json?lastRoute=%2Fapp%2Flist 500 in 2262ms
 GET /login?lastRoute=%2Fapp%2Flist 500 in 8175ms
 ⨯ N [Error]: Error serializing `.ChineseRedirectUrl` returned from `getServerSideProps` in "/login".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
    at r (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:446)
    at /home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:683
    at Array.every (<anonymous>)
    at r (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:580)
    at $ (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:1100)
    at e8 (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:25:1525)
    at async doRender (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1425:30)
    at async cacheEntry.responseCache.get.routeKind (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1931:24)
    at async DevServer.renderToResponseImpl (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:1969:32)
    at async DevServer.pipeImpl (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/base-server.js:816:17)
    at async /home/simply/XDU/simply/FastGPT/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.9_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_sass@1.77.8/node_modules/next/dist/server/dev/next-dev-server.js:339:20 {
  page: '/login'
}
@c121914yu

**Comment by c121914yu** [comment]
开发环境加个判断可以解决：
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/b67ebc10-16b9-418c-9f0c-07e40105a3b3">
