### ISSUE TITLE
更新.13后，部分既往工作流无法打开

### ISSUE THREAD

**Issue by mycyg** [labring/FastGPT#3198]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 4.8.13

**问题描述, 日志截图**
既往工作流打开后报错。
F11控制台信息如下：
TypeError: Cannot read properties of undefined (reading '_f')
    at ref (VM18375 62516-3af914a206c3b92b.js:1:20282)
    at aO (framework-61d8b7214f67f72f.js:9:62330)
    at uI (framework-61d8b7214f67f72f.js:9:84055)
    at uY (framework-61d8b7214f67f72f.js:9:90435)
    at e (framework-61d8b7214f67f72f.js:9:111030)
    at framework-61d8b7214f67f72f.js:9:111041
    at oI (framework-61d8b7214f67f72f.js:9:111553)
    at oC (framework-61d8b7214f67f72f.js:9:96182)
    at r8 (framework-61d8b7214f67f72f.js:9:44812)
    at framework-61d8b7214f67f72f.js:9:111547
a5 @ framework-61d8b7214f67f72f.js:9
a.componentDidCatch.t.callback @ framework-61d8b7214f67f72f.js:9
lX @ framework-61d8b7214f67f72f.js:9
uY @ framework-61d8b7214f67f72f.js:9
e @ framework-61d8b7214f67f72f.js:9
（匿名） @ framework-61d8b7214f67f72f.js:9
oI @ framework-61d8b7214f67f72f.js:9
oC @ framework-61d8b7214f67f72f.js:9
r8 @ framework-61d8b7214f67f72f.js:9
（匿名） @ framework-61d8b7214f67f72f.js:9
oI @ framework-61d8b7214f67f72f.js:9
oS @ framework-61d8b7214f67f72f.js:9
x @ framework-61d8b7214f67f72f.js:33
T @ framework-61d8b7214f67f72f.js:33了解此错误AI
main-838bc40712f8f836.js:1 TypeError: Cannot read properties of undefined (reading '_f')
    at ref (VM18375 62516-3af914a206c3b92b.js:1:20282)
    at aO (framework-61d8b7214f67f72f.js:9:62330)
    at uI (framework-61d8b7214f67f72f.js:9:84055)
    at uY (framework-61d8b7214f67f72f.js:9:90435)
    at e (framework-61d8b7214f67f72f.js:9:111030)
    at framework-61d8b7214f67f72f.js:9:111041
    at oI (framework-61d8b7214f67f72f.js:9:111553)
    at oC (framework-61d8b7214f67f72f.js:9:96182)
    at r8 (framework-61d8b7214f67f72f.js:9:44812)
    at framework-61d8b7214f67f72f.js:9:111547
Z @ main-838bc40712f8f836.js:1
fn @ main-838bc40712f8f836.js:1
componentDidCatch @ main-838bc40712f8f836.js:1
a.componentDidCatch.t.callback @ framework-61d8b7214f67f72f.js:9
lX @ framework-61d8b7214f67f72f.js:9
uY @ framework-61d8b7214f67f72f.js:9
e @ framework-61d8b7214f67f72f.js:9
（匿名） @ framework-61d8b7214f67f72f.js:9
oI @ framework-61d8b7214f67f72f.js:9
oC @ framework-61d8b7214f67f72f.js:9
r8 @ framework-61d8b7214f67f72f.js:9
（匿名） @ framework-61d8b7214f67f72f.js:9
oI @ framework-61d8b7214f67f72f.js:9
oS @ framework-61d8b7214f67f72f.js:9
x @ framework-61d8b7214f67f72f.js:33
T @ framework-61d8b7214f67f72f.js:33了解此错误AI
main-838bc40712f8f836.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Z @ main-838bc40712f8f836.js:1
fn @ main-838bc40712f8f836.js:1
componentDidCatch @ main-838bc40712f8f836.js:1
a.componentDidCatch.t.callback @ framework-61d8b7214f67f72f.js:9
lX @ framework-61d8b7214f67f72f.js:9
uY @ framework-61d8b7214f67f72f.js:9
e @ framework-61d8b7214f67f72f.js:9
（匿名） @ framework-61d8b7214f67f72f.js:9
oI @ framework-61d8b7214f67f72f.js:9
oC @ framework-61d8b7214f67f72f.js:9
r8 @ framework-61d8b7214f67f72f.js:9
（匿名） @ framework-61d8b7214f67f72f.js:9
oI @ framework-61d8b7214f67f72f.js:9
oS @ framework-61d8b7214f67f72f.js:9
x @ framework-61d8b7214f67f72f.js:33
T @ framework-61d8b7214f67f72f.js:33了解此错误AI
framework-61d8b7214f67f72f.js:9 TypeError: e.changeLanguage is not a function
    at n (_app-73b283fb75001c8d.js:25:8577)
    at i (_app-73b283fb75001c8d.js:25:8631)
    at _app-73b283fb75001c8d.js:25:13611
    at _app-73b283fb75001c8d.js:6:94100
    at uI (framework-61d8b7214f67f72f.js:9:84055)
    at oU (framework-61d8b7214f67f72f.js:9:113101)
    at oC (framework-61d8b7214f67f72f.js:9:95920)
    at r8 (framework-61d8b7214f67f72f.js:9:44812)
    at framework-61d8b7214f67f72f.js:9:111547
    at oI (framework-61d8b7214f67f72f.js:9:111553)
a5 @ framework-61d8b7214f67f72f.js:9
a.componentDidCatch.t.callback @ framework-61d8b7214f67f72f.js:9
lX @ framework-61d8b7214f67f72f.js:9
uY @ framework-61d8b7214f67f72f.js:9
e @ framework-61d8b7214f67f72f.js:9
（匿名） @ framework-61d8b7214f67f72f.js:9
oI @ framework-61d8b7214f67f72f.js:9
oC @ framework-61d8b7214f67f72f.js:9
r8 @ framework-61d8b7214f67f72f.js:9
（匿名） @ framework-61d8b7214f67f72f.js:9
oI @ framework-61d8b7214f67f72f.js:9
oS @ framework-61d8b7214f67f72f.js:9
x @ framework-61d8b7214f67f72f.js:33
T @ framework-61d8b7214f67f72f.js:33了解此错误AI
main-838bc40712f8f836.js:1 TypeError: e.changeLanguage is not a function
    at n (_app-73b283fb75001c8d.js:25:8577)
    at i (_app-73b283fb75001c8d.js:25:8631)
    at _app-73b283fb75001c8d.js:25:13611
    at _app-73b283fb75001c8d.js:6:94100
    at uI (framework-61d8b7214f67f72f.js:9:84055)
    at oU (framework-61d8b7214f67f72f.js:9:113101)
    at oC (framework-61d8b7214f67f72f.js:9:95920)
    at r8 (framework-61d8b7214f67f72f.js:9:44812)
    at framework-61d8b7214f67f72f.js:9:111547
    at oI (framework-61d8b7214f67f72f.js:9:111553)
Z @ main-838bc40712f8f836.js:1
fn @ main-838bc40712f8f836.js:1
componentDidCatch @ main-838bc40712f8f836.js:1
a.componentDidCatch.t.callback @ framework-61d8b7214f67f72f.js:9
lX @ framework-61d8b7214f67f72f.js:9
uY @ framework-61d8b7214f67f72f.js:9
e @ framework-61d8b7214f67f72f.js:9
（匿名） @ framework-61d8b7214f67f72f.js:9
oI @ framework-61d8b7214f67f72f.js:9
oC @ framework-61d8b7214f67f72f.js:9
r8 @ framework-61d8b7214f67f72f.js:9
（匿名） @ framework-61d8b7214f67f72f.js:9
oI @ framework-61d8b7214f67f72f.js:9
oS @ framework-61d8b7214f67f72f.js:9
x @ framework-61d8b7214f67f72f.js:33
T @ framework-61d8b7214f67f72f.js:33了解此错误AI
main-838bc40712f8f836.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

**复现步骤**
没办法导出之前的json，此前嵌入了较多js代码？可能是这个原因？

**预期结果**
能修复或者提供后台导出既往工作流的功能，以便于重新编排，恢复数据。

**相关截图**
![image](https://github.com/user-attachments/assets/481f6a66-4a5a-44af-bf68-b4e4187ed88e)
![image](https://github.com/user-attachments/assets/56952a1a-1391-4ac0-aa51-167df6eba3df)

**Comment by c121914yu** [comment]
测试示例里没法复现，需要个能复现的例子。
