### ISSUE TITLE
4811升级4813后无法向量化

### ISSUE THREAD

**Issue by xy3xy3** [labring/FastGPT#3219]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [ x] 私有部署版本, 具体版本号: 4.8.13

**问题描述, 日志截图**
```
[Error] 2024-11-23 03:41:37 Embedding Error
[Error] 2024-11-23 03:41:37 Api response error: /api/core/dataset/data/insertData, (request id: 202411231141364118978567JpXGoQl)
{
message: '401 (request id: 202411231141364118978567JpXGoQl)',
stack: 'Error: 401 (request id: 202411231141364118978567JpXGoQl)\n' +
' at tQ.generate (/app/projects/app/.next/server/chunks/12439.js:19:112053)\n' +
' at rd.makeStatusError (/app/projects/app/.next/server/chunks/12439.js:19:103694)\n' +
' at rd.makeRequest (/app/projects/app/.next/server/chunks/12439.js:19:104617)\n' +
' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
' at async u (/app/projects/app/.next/server/chunks/51338.js:242:2200)\n' +
' at async f (/app/projects/app/.next/server/chunks/51338.js:211:13738)\n' +
' at async Promise.all (index 0)\n' +
' at async c (/app/projects/app/.next/server/chunks/51338.js:422:25566)\n' +
' at async y (/app/projects/app/.next/server/pages/api/core/dataset/data/insertData.js:1:9596)\n' +
' at async /app/projects/app/.next/server/pages/api/core/dataset/create.js:1:5897'
}
{
message: '401 (request id: 202411231141364118978567JpXGoQl)',
stack: 'Error: 401 (request id: 202411231141364118978567JpXGoQl)\n' +
' at tQ.generate (/app/projects/app/.next/server/chunks/12439.js:19:112053)\n' +
' at rd.makeStatusError (/app/projects/app/.next/server/chunks/12439.js:19:103694)\n' +
' at rd.makeRequest (/app/projects/app/.next/server/chunks/12439.js:19:104617)\n' +
' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
' at async u (/app/projects/app/.next/server/chunks/51338.js:242:2200)\n' +
' at async f (/app/projects/app/.next/server/chunks/51338.js:211:13738)\n' +
' at async Promise.all (index 0)\n' +
' at async c (/app/projects/app/.next/server/chunks/51338.js:422:25566)\n' +
' at async y (/app/projects/app/.next/server/pages/api/core/dataset/data/insertData.js:1:9596)\n' +
' at async /app/projects/app/.next/server/pages/api/core/dataset/create.js:1:5897'
}
[Error] 2024-11-23 03:41:44 Embedding Error
{
message: '401 (request id: 202411231141441103302448STyn6mE)',
stack: 'Error: 401 (request id: 202411231141441103302448STyn6mE)\n' +
' at tQ.generate (/app/projects/app/.next/server/chunks/12439.js:19:112053)\n' +
' at rd.makeStatusError (/app/projects/app/.next/server/chunks/12439.js:19:103694)\n' +
' at rd.makeRequest (/app/projects/app/.next/server/chunks/12439.js:19:104617)\n' +
' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
' at async u (/app/projects/app/.next/server/chunks/51338.js:242:2200)\n' +
' at async f (/app/projects/app/.next/server/chunks/51338.js:211:13738)\n' +
' at async Promise.all (index 0)\n' +
' at async c (/app/projects/app/.next/server/chunks/51338.js:422:25566)\n' +
' at async y (/app/projects/app/.next/server/pages/api/core/dataset/data/insertData.js:1:9596)\n' +
' at async /app/projects/app/.next/server/pages/api/core/dataset/create.js:1:5897'
}
[Error] 2024-11-23 03:41:44 Api response error: /api/core/dataset/data/insertData, (request id: 202411231141441103302448STyn6mE)
{
message: '401 (request id: 202411231141441103302448STyn6mE)',
stack: 'Error: 401 (request id: 202411231141441103302448STyn6mE)\n' +
' at tQ.generate (/app/projects/app/.next/server/chunks/12439.js:19:112053)\n' +
' at rd.makeStatusError (/app/projects/app/.next/server/chunks/12439.js:19:103694)\n' +
' at rd.makeRequest (/app/projects/app/.next/server/chunks/12439.js:19:104617)\n' +
' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
' at async u (/app/projects/app/.next/server/chunks/51338.js:242:2200)\n' +
' at async f (/app/projects/app/.next/server/chunks/51338.js:211:13738)\n' +
' at async Promise.all (index 0)\n' +
' at async c (/app/projects/app/.next/server/chunks/51338.js:422:25566)\n' +
' at async y (/app/projects/app/.next/server/pages/api/core/dataset/data/insertData.js:1:9596)\n' +
' at async /app/projects/app/.next/server/pages/api/core/dataset/create.js:1:5897'
}
```
**复现步骤**
插入一条数据到知识库或者api创建数据
**预期结果**
正常插入
**相关截图**
![image](https://github.com/user-attachments/assets/18b2dcf3-8526-4b9f-a819-c7f57db4b5d4)

**Comment by xy3xy3** [comment]
可能是不支持硅基流动模型名字？
```
  "vectorModels": [
    {
      "model": "Pro/BAAI/bge-m3",
      "name": "bge-m3",
      "inputPrice": 0,
      "outputPrice": 0,
      "defaultToken": 700,
      "maxToken": 8000,
      "weight": 100
    },
```

**Comment by xy3xy3** [comment]
我的key问题

**Comment by ZhiGangCai** [comment]
> 我的key问题

请问一下，是哪个key，我也碰到了这个问题
