### ISSUE TITLE
升级3.8.14报错Init system error Error: ENOENT: no such file or directory, open '/app/projects/app/.next/proto/proto/schema.proto'

### ISSUE THREAD

**Issue by 459359351** [labring/FastGPT#3245]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.tryfastgpt.ai/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本, 具体版本号: 3.8.14

**问题描述, 日志截图**
fastgpt升级到3.8.14后，docker无法启动，报错如下
```
# 日志报错如下
Init system error Error: ENOENT: no such file or directory, open '/app/projects/app/.next/proto/proto/schema.proto'
    at Object.openSync (node:fs:573:18)
    at Object.readFileSync (node:fs:452:35)
    at f (/app/projects/app/.next/server/chunks/32490.js:45:64809)
    at d.e [as load] (/app/projects/app/.next/server/chunks/32490.js:45:65047)
    at d.loadSync (/app/projects/app/.next/server/chunks/32490.js:45:65169)
    at Object.s [as loadSync] (/app/projects/app/.next/server/chunks/32490.js:45:40190)
    at new f (/app/projects/app/.next/server/chunks/32490.js:35:41549)
    at new a (/app/projects/app/.next/server/chunks/32490.js:35:44021)
    at new o (/app/projects/app/.next/server/chunks/32490.js:35:52044)
    at new o (/app/projects/app/.next/server/chunks/32490.js:35:67911) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/projects/app/.next/proto/proto/schema.proto'
```
**复现步骤**
升级fastgpt至3.8.14
**预期结果**
正常启动
**相关截图**
<img width="820" alt="image" src="https://github.com/user-attachments/assets/73f50376-e75f-42a9-aadb-cbfb3523b474">

**Comment by c121914yu** [comment]
啥环境？去 next 搜下有没有类似问题。

**Comment by c121914yu** [comment]
https://github.com/labring/FastGPT/releases/tag/v4.8.14-milvus-fix milvus 版本问题，可以等镜像构建完，用这个镜像。
