### ISSUE TITLE
点击工作流应用提示出现未捕获的异常

### ISSUE THREAD

**Issue by Happy5** [labring/FastGPT#3397]
docker-compose.yml文件仅修改了fastgpt和mysql的端口
服务器部署成功后（windows+chrome访问，已关闭浏览器翻译功能）
新建工作流，点击工作流，进入页面后，隔一会就自动退出，页面提示如下：
------------------------------------
出现未捕获的异常。
1. 私有部署用户，90%由于配置文件不正确导致。
2. 部分系统不兼容相关API。大部分是苹果的safari 浏览器导致，可以尝试更换 chrome。 
3. 请关闭浏览器翻译功能，部分翻译导致页面崩溃。

排除3后，打开控制台的 console 查看具体报错信息。
如果提示 xxx undefined 的话，就是配置文件有错误。

console报错如下：
not available
Expression
not available
﻿
framework-61d8b7214f67f72f.js:9 TypeError: Cannot read properties of undefined (reading 'includes')
    at 75897-82def12d1617ba0d.js:1:18862
    at Array.filter (<anonymous>)
    at _ (75897-82def12d1617ba0d.js:1:18776)
    at 90432-f79c6b267300e706.js:1:6557
    at Array.map (<anonymous>)
    at 90432-f79c6b267300e706.js:1:6352
    at Object.useMemo (framework-61d8b7214f67f72f.js:9:64712)
    at n.useMemo (framework-61d8b7214f67f72f.js:25:5995)
    at w (90432-f79c6b267300e706.js:1:6210)
    at 90432-f79c6b267300e706.js:1:7101
main-838bc40712f8f836.js:1 TypeError: Cannot read properties of undefined (reading 'includes')
    at 75897-82def12d1617ba0d.js:1:18862
    at Array.filter (<anonymous>)
    at _ (75897-82def12d1617ba0d.js:1:18776)
    at 90432-f79c6b267300e706.js:1:6557
    at Array.map (<anonymous>)
    at 90432-f79c6b267300e706.js:1:6352
    at Object.useMemo (framework-61d8b7214f67f72f.js:9:64712)
    at n.useMemo (framework-61d8b7214f67f72f.js:25:5995)
    at w (90432-f79c6b267300e706.js:1:6210)
    at 90432-f79c6b267300e706.js:1:7101
main-838bc40712f8f836.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
framework-61d8b7214f67f72f.js:9 TypeError: Cannot read properties of undefined (reading 'includes')
    at 75897-82def12d1617ba0d.js:1:18862
    at Array.filter (<anonymous>)
    at _ (75897-82def12d1617ba0d.js:1:18776)
    at 90432-f79c6b267300e706.js:1:6557
    at Array.map (<anonymous>)
    at 90432-f79c6b267300e706.js:1:6352
    at Object.useMemo (framework-61d8b7214f67f72f.js:9:64712)
    at n.useMemo (framework-61d8b7214f67f72f.js:25:5995)
    at w (90432-f79c6b267300e706.js:1:6210)
    at 90432-f79c6b267300e706.js:1:7101
main-838bc40712f8f836.js:1 TypeError: Cannot read properties of undefined (reading 'includes')
    at 75897-82def12d1617ba0d.js:1:18862
    at Array.filter (<anonymous>)
    at _ (75897-82def12d1617ba0d.js:1:18776)
    at 90432-f79c6b267300e706.js:1:6557
    at Array.map (<anonymous>)
    at 90432-f79c6b267300e706.js:1:6352
    at Object.useMemo (framework-61d8b7214f67f72f.js:9:64712)
    at n.useMemo (framework-61d8b7214f67f72f.js:25:5995)
    at w (90432-f79c6b267300e706.js:1:6210)
    at 90432-f79c6b267300e706.js:1:7101
main-838bc40712f8f836.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
framework-61d8b7214f67f72f.js:9 TypeError: Cannot read properties of undefined (reading 'includes')
    at 75897-82def12d1617ba0d.js:1:18862
    at Array.filter (<anonymous>)
    at _ (75897-82def12d1617ba0d.js:1:18776)
    at 90432-f79c6b267300e706.js:1:6557
    at Array.map (<anonymous>)
    at 90432-f79c6b267300e706.js:1:6352
    at Object.useMemo (framework-61d8b7214f67f72f.js:9:64712)
    at n.useMemo (framework-61d8b7214f67f72f.js:25:5995)
    at w (90432-f79c6b267300e706.js:1:6210)
    at 90432-f79c6b267300e706.js:1:7101
main-838bc40712f8f836.js:1 TypeError: Cannot read properties of undefined (reading 'includes')
    at 75897-82def12d1617ba0d.js:1:18862
    at Array.filter (<anonymous>)
    at _ (75897-82def12d1617ba0d.js:1:18776)
    at 90432-f79c6b267300e706.js:1:6557
    at Array.map (<anonymous>)
    at 90432-f79c6b267300e706.js:1:6352
    at Object.useMemo (framework-61d8b7214f67f72f.js:9:64712)
    at n.useMemo (framework-61d8b7214f67f72f.js:25:5995)
    at w (90432-f79c6b267300e706.js:1:6210)
    at 90432-f79c6b267300e706.js:1:7101
main-838bc40712f8f836.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
framework-61d8b7214f67f72f.js:9 TypeError: Cannot read properties of undefined (reading 'includes')
    at 75897-82def12d1617ba0d.js:1:18862
    at Array.filter (<anonymous>)
    at _ (75897-82def12d1617ba0d.js:1:18776)
    at 90432-f79c6b267300e706.js:1:6557
    at Array.map (<anonymous>)
    at 90432-f79c6b267300e706.js:1:6352
    at Object.useMemo (framework-61d8b7214f67f72f.js:9:64712)
    at n.useMemo (framework-61d8b7214f67f72f.js:25:5995)
    at w (90432-f79c6b267300e706.js:1:6210)
    at 90432-f79c6b267300e706.js:1:7101
main-838bc40712f8f836.js:1 TypeError: Cannot read properties of undefined (reading 'includes')
    at 75897-82def12d1617ba0d.js:1:18862
    at Array.filter (<anonymous>)
    at _ (75897-82def12d1617ba0d.js:1:18776)
    at 90432-f79c6b267300e706.js:1:6557
    at Array.map (<anonymous>)
    at 90432-f79c6b267300e706.js:1:6352
    at Object.useMemo (framework-61d8b7214f67f72f.js:9:64712)
    at n.useMemo (framework-61d8b7214f67f72f.js:25:5995)
    at w (90432-f79c6b267300e706.js:1:6210)
    at 90432-f79c6b267300e706.js:1:7101
main-838bc40712f8f836.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
framework-61d8b7214f67f72f.js:9 TypeError: Cannot read properties of undefined (reading 'includes')
    at 75897-82def12d1617ba0d.js:1:18862
    at Array.filter (<anonymous>)
    at _ (75897-82def12d1617ba0d.js:1:18776)
    at 90432-f79c6b267300e706.js:1:6557
    at Array.map (<anonymous>)
    at 90432-f79c6b267300e706.js:1:6352
    at Object.useMemo (framework-61d8b7214f67f72f.js:9:64712)
    at n.useMemo (framework-61d8b7214f67f72f.js:25:5995)
    at w (90432-f79c6b267300e706.js:1:6210)
    at 90432-f79c6b267300e706.js:1:7101
main-838bc40712f8f836.js:1 TypeError: Cannot read properties of undefined (reading 'includes')
    at 75897-82def12d1617ba0d.js:1:18862
    at Array.filter (<anonymous>)
    at _ (75897-82def12d1617ba0d.js:1:18776)
    at 90432-f79c6b267300e706.js:1:6557
    at Array.map (<anonymous>)
    at 90432-f79c6b267300e706.js:1:6352
    at Object.useMemo (framework-61d8b7214f67f72f.js:9:64712)
    at n.useMemo (framework-61d8b7214f67f72f.js:25:5995)
    at w (90432-f79c6b267300e706.js:1:6210)
    at 90432-f79c6b267300e706.js:1:7101
main-838bc40712f8f836.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
4
main-838bc40712f8f836.js:1 Error rendering page:  Error: Cancel rendering route
    at c (main-838bc40712f8f836.js:1:13479)
    at main-838bc40712f8f836.js:1:13431
    at new Promise (<anonymous>)
    at es (main-838bc40712f8f836.js:1:13408)
    at main-838bc40712f8f836.js:1:11652
_app-399ead6e28adfebc.js:360 react-i18next:: You will need to pass in an i18next instance by using initReactI18next
_app-399ead6e28adfebc.js:25 Uncaught (in promise) TypeError: e.hasResourceBundle is not a function
    at n (_app-399ead6e28adfebc.js:25:8937)

**Comment by c121914yu** [comment]
选择空白模板，不要选问题分类模板。
