### ISSUE TITLE
When executing 451 initialization prompt, what is the reason?

### ISSUE THREAD

**Issue by shiliu2023** [labring/FastGPT#448]
at new tJ (/app/projects/app/.next/server/chunks/1952.js:899:62863)
    at o (/app/projects/app/.next/server/pages/api/admin/initv451.js:14:797)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async q (/app/projects/app/.next/server/pages/api/admin/initv451.js:14:1224)
    at async y (/app/projects/app/.next/server/pages/api/admin/initv451.js:1:2250)
eG [BSONError]: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
    at new tJ (/app/projects/app/.next/server/chunks/1952.js:899:62863)
    at o (/app/projects/app/.next/server/pages/api/admin/initv451.js:14:797)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async q (/app/projects/app/.next/server/pages/api/admin/initv451.js:14:1224)
    at async y (/app/projects/app/.next/server/pages/api/admin/initv451.js:1:2250)
eG [BSONError]: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer

**Comment by c121914yu** [comment]
问题重复 https://github.com/labring/FastGPT/issues/449
