### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useMemo')

### ISSUE THREAD

**Issue by Yanshang1991** [labring/FastGPT#476]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
1. 更新最新的代码之后，本地运行报错：`ReferenceError: window is not defined`
这个问题应该是echarts库里面用到了客户端的windows，修改components/Markdown/index.tsx可以解决
`const EChartsCodeBlock = dynamic(() => import('./img/EChartsCodeBlock'), {ssr:false});`
2. 解决上诉问题之后，运行报错：`TypeError: Cannot read properties of null (reading 'useMemo')`，相关日志：
`
TypeError: Cannot read properties of null (reading 'useMemo')
    at useMemo (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.development.js:1650:21)
    at AppWithTranslation (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+next-i18next@13.3.0_i18next@22.5.1_next@13.5.2_react-i18next@12.3.1_react@18.2.0/node_modules/next-i18next/dist/commonjs/appWithTranslation.js:68:35)
    at renderWithHooks (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/yszb/Documents/PycharmProjects/FastGPT/node_modules/.pnpm/registry.npmmirror.com+react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12) {
  page: '/'
}
`
**复现步骤**
本地运行
**预期结果**
正常运行
**相关截图**
无

**Comment by Yanshang1991** [comment]
我本地用的是node21，改成node18，清包重试之后正常了。应该是node21适配有问题。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I was using node21 locally and changed it to node18. After clearing the package and trying again, it became normal. There should be a problem with node21 adaptation.

**Comment by TuXinKJ** [comment]
最新的main分支代码，我使用node v18.10.0 和 v20.10.0 发现了这个问题，上个月的代码是用node 18.10.0是可以的

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
For the latest main branch code, I discovered this problem using node v18.10.0 and v20.10.0. Last month’s code was ok using node 18.10.0.

**Comment by Hel5ing** [comment]
same issue with node v20.3.1

**Comment by youmengme** [comment]
确实无法运行。我试了node@16 node18.0 node@18.10 node@19 node@20 都运行不起来 求解决~~

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It really doesn't work. I tried node@16 node18.0 node@18.10 node@19 node@20 but it didn’t work. Please solve it~~

**Comment by youmengme** [comment]
解决方案：
```bash
find . -type d -name "node_modules" -prune -exec rm -rf {} +
```
在项目根目录执行上述代码删除项目里的所有node_modules文件夹，然后将node版本切换至v18.0.0 然后在项目根目录执行`pnpm install`

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
solution:
```bash
find . -type d -name "node_modules" -prune -exec rm -rf {} +
```
Execute the above code in the project root directory to delete all node_modules folders in the project, then switch the node version to v18.0.0 and then execute `pnpm install` in the project root directory
