### ISSUE TITLE
升级4.6版本后对话提示431

### ISSUE THREAD

**Issue by vary** [labring/FastGPT#479]
**例行检查**

- [ x ] 我已确认目前没有类似 issue
- [ x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x  ] 私有部署版本

**问题描述**
新建一个问题分类+知识库的应用，直接对话如下图所示，但是新建简单应用对话是正常的
已确认不是nginx的转发配置问题，后台的日志如下：
{
  stack: 'Error: 431 <html>\n' +
    '  <head>\n' +
    '    <title>Request Header Fields Too Large</title>\n' +
    '  </head>\n' +
    '  <body>\n' +
    '    <h1><p>Request Header Fields Too Large</p></h1>\n' +
    '    Error parsing headers: &#x27;limit request headers fields&#x27;\n' +
    '  </body>\n' +
    '</html>\n' +
    '\n' +
    '    at APIError.generate (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/error.mjs:62:16)\n' +
    '    at OpenAI.makeStatusError (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/core.mjs:244:25)\n' +
    '    at OpenAI.makeRequest (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/core.mjs:283:30)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async m (/app/projects/app/.next/server/chunks/8484.js:44:369)\n' +
    '    at async Object.h [as classifyQuestion] (/app/projects/app/.next/server/chunks/8484.js:39:678)\n' +
    '    at async D (/app/projects/app/.next/server/chunks/8484.js:50:4784)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 2)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Promise.all (index 2)\n' +
    '    at async I (/app/projects/app/.next/server/chunks/8484.js:50:5852)\n' +
    '    at async /app/projects/app/.next/server/chunks/1282.js:1:2726'
}
[ERROR]: 2023-11-16 08:26:32: sse error: 431 <html>
  <head>
    <title>Request Header Fields Too Large</title>
  </head>
  <body>
    <h1><p>Request Header Fields Too Large</p></h1>
    Error parsing headers: &#x27;limit request headers fields&#x27;
  </body>
</html>
**复现步骤**
新建一个问题分类+知识库的应用，直接对话就可以复现
**预期结果**
像之前的版本一样正常，不报错。
**相关截图**
<img width="1484" alt="image" src="https://github.com/labring/FastGPT/assets/3312460/c00b7c54-3803-445d-a177-47d06df5858c">

**Comment by c121914yu** [comment]
无法复现。
请提供完整网关配置，如果用了中转，页需要提供中转的网关配置，

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Sorry, Alibaba Cloud transfer problem, frustrating to death😓
