### ISSUE TITLE
There is no available channel for model text-embedding-ada-002 under the current group default.

### ISSUE THREAD

**Issue by Jesn** [labring/FastGPT#509]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [x] 私有部署版本  
- [x] ghcr.io/labring/fastgpt:v4.6.1

**问题描述**
```
Embedding Error InternalServerError: 503 当前分组 default 下对于模型 text-embedding-ada-002 无可用渠道 (request id: 2023112319511878560700aZyi3fOR)
    at APIError.generate (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/error.mjs:60:20)
    at OpenAI.makeStatusError (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/core.mjs:244:25)
    at OpenAI.makeRequest (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/core.mjs:283:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async o (/app/projects/app/.next/server/chunks/2382.js:72:2419)
    at async m (/app/projects/app/.next/server/chunks/2382.js:74:1866)
    at async Promise.all (index 0)
    at async c (/app/projects/app/.next/server/chunks/2382.js:73:161)
    at async p (/app/projects/app/.next/server/chunks/2382.js:79:2402) {
  status: 503,
  headers: {
    'content-length': '167',
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 23 Nov 2023 11:51:18 GMT',
    'x-oneapi-request-id': '2023112319511878560700aZyi3fOR'
  },
  error: {
    message: '当前分组 default 下对于模型 text-embedding-ada-002 无可用渠道 (request id: 2023112319511878560700aZyi3fOR)',
    type: 'one_api_error'
  },
  code: undefined,
  param: undefined,
  type: 'one_api_error'
}
```

**复现步骤**
 添加知识库后，日志中就出现了该日志

**相关截图**
<img width="1340" alt="image" src="https://github.com/labring/FastGPT/assets/5728274/165a4716-ec47-4a53-83ad-a535098502f5">

**Comment by Jesn** [comment]
问题已经找到，需要在one-api 渠道中添加 `text-embedding-ada-002` 模型

<img width="1377" alt="image" src="https://github.com/labring/FastGPT/assets/5728274/84b90924-0fcf-4283-a29f-4812336f5772">

添加完成后，Task就自动执行了
<img width="1250" alt="image" src="https://github.com/labring/FastGPT/assets/5728274/923614a7-2a99-443c-b337-ad4f73dd5df4">
<img width="1445" alt="image" src="https://github.com/labring/FastGPT/assets/5728274/1475cb5f-21bb-4ae3-a86a-df0c480599cf">

**Comment by Jesn** [comment]
在对话过程中还需要在  one-api 添加

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
During the conversation, you also need to add in one-api
