### ISSUE TITLE
After opening the [Next] guide, the console output error at async c (/app/projects/app/.next/server/pages/api/core/ai/agent/createQuestionGuide. js:1:3163

### ISSUE THREAD

**Issue by leoterry-ulrica** [labring/FastGPT#575]
```
{
  stack: 'Error: 400  (request id: 20231207170859382448428osT77lIq)\n' +
    '    at APIError.generate (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/error.mjs:39:20)\n' +
    '    at OpenAI.makeStatusError (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/core.mjs:244:25)\n' +
    '    at OpenAI.makeRequest (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/core.mjs:283:30)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async o (/app/projects/app/.next/server/pages/api/core/ai/agent/createQuestionGuide.js:1:1963)\n' +
    '    at async c (/app/projects/app/.next/server/pages/api/core/ai/agent/createQuestionGuide.js:1:3163)'
}

```

**Comment by c121914yu** [comment]
看着是上游g了
