### ISSUE TITLE
As long as you add [content extraction component], an error will be thrown: at async Object.m [as contentExtract] (/app/projects/app/.next/server/chunks/8484.js:44:704 )\n'

### ISSUE THREAD

**Issue by leoterry-ulrica** [labring/FastGPT#581]
```
[ERROR]: 2023-12-06 12:35:51: sse error:  (request id: 20231206203551954033171t848XxVK)
{
  stack: 'Error: 400  (request id: 20231206203654951531318xnyny49R)\n' +
    '    at APIError.generate (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/error.mjs:39:20)\n' +
    '    at OpenAI.makeStatusError (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/core.mjs:244:25)\n' +
    '    at OpenAI.makeRequest (file:///app/node_modules/.pnpm/registry.npmmirror.com+openai@4.16.1_encoding@0.1.13/node_modules/openai/core.mjs:283:30)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async d (/app/projects/app/.next/server/chunks/8484.js:45:141)\n' +
    '    at async Object.m [as contentExtract] (/app/projects/app/.next/server/chunks/8484.js:44:704)\n' +
    '    at async N (/app/projects/app/.next/server/chunks/8484.js:49:5095)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Promise.all (index 1)\n' +
    '    at async Y (/app/projects/app/.next/server/chunks/8484.js:49:6164)\n' +
    '    at async c (/app/projects/app/.next/server/pages/api/core/chat/chatTest.js:1:2511)' 
}
```

**Comment by leoterry-ulrica** [comment]
@c121914yu 麻烦帮忙排查一下  已经更换过全新环境，重新部署依然是这个问题。上一个版本是正常的。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@c121914yu Please help to troubleshoot. I have changed to a new environment and the problem is still the same after redeployment. The previous version was normal.

**Comment by tangjianbei** [comment]
遇到一样的问题，版本4.6.6.1，使用webclient方式调用接口

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Encountered the same problem, version 4.6.6.1, using webclient method to call the interface
