### ISSUE TITLE
Function supports enterprise WeChat-automatic reply to messages within WeChat customer service

### ISSUE THREAD

**Issue by NO10Supper** [labring/FastGPT#643]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 features
- [x ] 我已确认我已升级到最新版本
- [x ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [x ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
增加支持企业微信-微信客服自动回复功能
**应用场景**
客户通过微信客服发起咨询，现在回复内容已经生成，但回复消息报错
**相关示例**

2023-12-20 19:43:20 - 回复内容： {"type":1,"content":"哈哈\n-----------\n抱歉，我无法理解您的问题，请提供更具体的信息或者问题，以便我能够帮助您。"} 

19:43:20 INFO PuppetService messageSend(7881299811924697, 哈哈
-----------
抱歉，我无法理解您的问题，请提供更具体的信息或者问题，以便我能够帮助您。) about to call grpc
2023-12-20 19:43:21 - 私聊发送消息失败 Error: 13 INTERNAL: WorkproErrorCode: 23060, processSendMsgRsp(7881299811924697) contentType: Unknown send message failed! cgi error code: (-4014) message: .
    at callErrorFromStatus (/bot/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/bot/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/bot/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/bot/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /bot/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/bot/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.messageSendText (/bot/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at node:internal/util:364:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:350:12)
    at PuppetService.messageSendText (file:///bot/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:1004:44)
    at file:///bot/node_modules/@juzi/wechaty/dist/esm/src/sayable/deliver-sayable.js:12:23
    at WechatifiedUserClass.say (file:///bot/node_modules/@juzi/wechaty/dist/esm/src/user-modules/contact.js:306:91)
    at WechatyImpl.contactSay (file:///bot/node_modules/wechaty-web-panel/dist/esm/src/common/index.js:269:27)
    at async dispatchFriendFilterByMsgType (file:///bot/node_modules/wechaty-web-panel/dist/esm/src/handlers/on-message.js:80:29) {
  code: 13,
  details: 'WorkproErrorCode: 23060, processSendMsgRsp(7881299811924697) contentType: Unknown send message failed! cgi error code: (-4014) message: .',
  metadata: Metadata {

**Comment by c121914yu** [comment]
和FastGPT没啥关系呢，这不是对接微信的问题么
