### ISSUE TITLE
docker stawky/m/m3e-large-api 內部出錯

### ISSUE THREAD

**Issue by AnsonCar** [labring/FastGPT#741]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
使用 docker run -p 6008:6008 --name=m3e-large-api stawky/m/m3e-large-api
成功運行，但docker內部報錯 
```
No sentence-transformers model found with name ./moka-ai_m3e-large. Creating a new one with MEAN pooling.
本次加载模型的设备为CPU.
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main    
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke  
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke   
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 416, in main   
    run(
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 587, in run    
    server.run()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run   
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve 
    config.load()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 467, in load 
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module  
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed       
  File "/app/localembedding.py", line 42, in <module>
    class ChatMessage(BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__        
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis  
  File "/usr/local/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
PS C:\Users\AnsonCar\Desktop\AIO> docker run -p 6008:6008 --name=m3e-large-api stawky/m3e-large-api
docker: Error response from daemon: Conflict. The container name "/m3e-large-api" is 
already in use by container "ee16d688e07120ad41e7c24c140e5aefe05e696468f9ec3c35b6bbf73927a11e". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.          docker run -p 6008:6008 --name=m3e-large-api stawky/m3e-large-apisonCar\Desktop\AIO>
docker: Error response from daemon: Conflict. The container name "/m3e-large-api" is 
already in use by container "ee16d688e07120ad41e7c24c140e5aefe05e696468f9ec3c35b6bbf73927a11e". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
PS C:\Users\AnsonCar\Desktop\AIO> docker run -p 6008:6008 --name=m3e-large-api stawky/m3e-large-api
No sentence-transformers model found with name ./moka-ai_m3e-large. Creating a new one with MEAN pooling.
本次加载模型的设备为CPU.
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main    
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke  
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke   
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 416, in main   
    run(
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 587, in run    
    server.run()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run   
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve 
    config.load()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 467, in load 
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module  
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed       
  File "/app/localembedding.py", line 42, in <module>
    class ChatMessage(BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__        
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis  
  File "/usr/local/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

**复现步骤**
docker run -p 6008:6008 --name=m3e-large-api stawky/m/m3e-large-api

**预期结果**
可以使用
```
curl --location --request POST 'http://192.168.xx.xx:6008/v1/embeddings' \
--header 'Authorization: Bearer sk-aaabbbcccdddeeefffggghhhiiijjjkkk' \
--header 'Content-Type: application/json' \
--data-raw '{
  "model": "m3e",
  "input": ["laf是什么"]
}'
```

**相关截图**
![螢幕截圖 2024-01-17 上午12 32 24](https://github.com/labring/FastGPT/assets/89959513/71c14e44-4862-4abe-8353-420937d8d9a4)

**Comment by stakeswky** [comment]
尝试拉一下阿里云的镜像，这个镜像的pydantic版本有问题，等待修复 @AnsonCar

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Try to pull the Alibaba Cloud image. There is a problem with the pydantic version of this image, waiting to be fixed @AnsonCar
