### ISSUE TITLE
dataset/data/insertData 404

### ISSUE THREAD

**Issue by shuaizai88** [labring/FastGPT#750]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x ] 我已确认目前没有类似 issue
- [x ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x ] 私有部署版本

**问题描述**
ubuntu docker部署后，手动录入知识库内容点击确认收入后提示404 status code (no body)
**复现步骤**
ubuntu docker部署后，手动录入知识库内容点击确认收入后提示404 status code (no body)
导入一个word后也是，后台好像在 跑定时任务然后也是404
**预期结果**
插入成功
**相关截图**
![image](https://github.com/labring/FastGPT/assets/32242038/c7680942-049c-497a-bca8-0a5a18f08588)

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
**Routine inspection**

[//]: # 'Fill x in the box to indicate tick'

- [x ] I have confirmed that there is currently no similar issue
- [x ] I have reviewed the project README in full, as well as the [project documentation](https://doc.fastgpt.in/docs/intro/)
- [x] I used my own key and confirmed that my key can be used normally
- [x] I understand and am willing to follow up on this issue, assist with testing and provide feedback
- [x] I understand and acknowledge the above content, and understand that project maintainers have limited energy. **Issues that do not follow the rules may be ignored or closed directly**

**your version**

- [ ] Public cloud version
- [x ] private deployment version

**Problem Description**
After ubuntu docker is deployed, manually enter the content of the knowledge base and click Confirm Revenue, and then it will prompt 404 status code (no body)
**Steps to reproduce**
After ubuntu docker is deployed, manually enter the content of the knowledge base and click Confirm Revenue, and then it will prompt 404 status code (no body)
The same thing happens after importing a word. The background seems to be running a scheduled task and then it also gets 404.
**expected outcome**
Inserted successfully
**Related screenshots**
![image](https://github.com/labring/FastGPT/assets/32242038/c7680942-049c-497a-bca8-0a5a18f08588)

**Comment by shuaizai88** [comment]
[ERROR] 2024-01-19 07:45:15 response error: 404 status code (no body) 
{
  stack: 'Error: 404 status code (no body)\n' +
    '    at eL.generate (/app/projects/app/.next/server/chunks/66031.js:23:67713)\n' +
    '    at tx.makeStatusError (/app/projects/app/.next/server/chunks/66031.js:23:79052)\n' +
    '    at tx.makeRequest (/app/projects/app/.next/server/chunks/66031.js:23:79786)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async b (/app/projects/app/.next/server/chunks/4367.js:33:852)\n' +
    '    at async w (/app/projects/app/.next/server/chunks/4367.js:25:382)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Q (/app/projects/app/.next/server/chunks/4367.js:81:161)\n' +
    '    at async /app/projects/app/.next/server/pages/api/core/dataset/data/insertData.js:1:2588'
}

**Comment by c121914yu** [comment]
向量模型不存在

**Comment by teeemoom** [comment]
请求网址:
http://localhost:3020/api/core/dataset/data/insertData
请求方法:
POST
状态代码:
500 Internal Server Error
远程地址:
[::1]:3020
引荐来源网址政策:
strict-origin-when-cross-origin  同样的问题，500错误

**Comment by teeemoom** [comment]
![微信截图_20231210120226](https://github.com/labring/FastGPT/assets/143974082/b527ae94-a5eb-47b9-b5c1-75873f1dad36)
2024-03-15 21:17:36 [ERROR] 2024-03-15 13:17:36 response error: 404 status code (no body) 
2024-03-15 21:17:36 {
2024-03-15 21:17:36   message: '404 status code (no body)',
2024-03-15 21:17:36   stack: 'Error: 404 status code (no body)\n' +
2024-03-15 21:17:36     '    at eL.generate (/app/projects/app/.next/server/chunks/53204.js:21:70115)\n' +
2024-03-15 21:17:36     '    at ax.makeStatusError (/app/projects/app/.next/server/chunks/53204.js:21:81454)\n' +
2024-03-15 21:17:36     '    at ax.makeRequest (/app/projects/app/.next/server/chunks/53204.js:21:82188)\n' +
2024-03-15 21:17:36     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-03-15 21:17:36     '    at async W (/app/projects/app/.next/server/chunks/82729.js:31:1242)\n' +
2024-03-15 21:17:36     '    at async w (/app/projects/app/.next/server/chunks/82729.js:23:399)\n' +
2024-03-15 21:17:36     '    at async Promise.all (index 0)\n' +
2024-03-15 21:17:36     '    at async I (/app/projects/app/.next/server/chunks/5182.js:54:15961)\n' +
2024-03-15 21:17:36     '    at async /app/projects/app/.next/server/pages/api/core/dataset/data/insertData.js:1:3064'
2024-03-15 21:17:36 }
2024-03-15 21:18:00 [INFO] 2024-03-15 13:18:00 [QA Queue] Done 
2024-03-15 21:18:00 [INFO] 2024-03-15 13:18:00 [Vector Queue] Done 
2024-03-15 21:19:00 [INFO] 2024-03-15 13:19:00 [QA Queue] Done 
2024-03-15 21:19:00 [INFO] 2024-03-15 13:19:00 [Vector Queue] Done 
2024-03-15 21:20:00 [INFO] 2024-03-15 13:20:00 [QA Queue] Done 
2024-03-15 21:20:00 [INFO] 2024-03-15 13:20:00 [Vector Queue] Done 
2024-03-15 21:21:00 Embedding Error ez [Error]: 404 status code (no body)
2024-03-15 21:21:00     at eL.generate (/app/projects/app/.next/server/chunks/53204.js:21:70115)
2024-03-15 21:21:00     at ax.makeStatusError (/app/projects/app/.next/server/chunks/53204.js:21:81454)
2024-03-15 21:21:00     at ax.makeRequest (/app/projects/app/.next/server/chunks/53204.js:21:82188)
2024-03-15 21:21:00     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-15 21:21:00     at async W (/app/projects/app/.next/server/chunks/82729.js:31:1242)
2024-03-15 21:21:00     at async w (/app/projects/app/.next/server/chunks/82729.js:23:399)
2024-03-15 21:21:00     at async Promise.all (index 0)
2024-03-15 21:21:00     at async I (/app/projects/app/.next/server/chunks/5182.js:54:15961)
2024-03-15 21:21:00     at async /app/projects/app/.next/server/pages/api/core/dataset/data/insertData.js:1:3064 {
2024-03-15 21:21:00   status: 404,
2024-03-15 21:21:00   headers: {
2024-03-15 21:21:00     'content-length': '22',
2024-03-15 21:21:00     'content-type': 'application/json',
2024-03-15 21:21:00     date: 'Fri, 15 Mar 2024 13:21:00 GMT',
2024-03-15 21:21:00     server: 'uvicorn'
2024-03-15 21:21:00   },
2024-03-15 21:21:00   error: undefined,
2024-03-15 21:21:00   code: undefined,
2024-03-15 21:21:00   param: undefined,
2024-03-15 21:21:00   type: undefined
2024-03-15 21:21:00 }
2024-03-15 21:21:00 [ERROR] 2024-03-15 13:21:00 response error: 404 status code (no body) 
2024-03-15 21:21:00 {
2024-03-15 21:21:00   message: '404 status code (no body)',
2024-03-15 21:21:00   stack: 'Error: 404 status code (no body)\n' +
2024-03-15 21:21:00     '    at eL.generate (/app/projects/app/.next/server/chunks/53204.js:21:70115)\n' +
2024-03-15 21:21:00     '    at ax.makeStatusError (/app/projects/app/.next/server/chunks/53204.js:21:81454)\n' +
2024-03-15 21:21:00     '    at ax.makeRequest (/app/projects/app/.next/server/chunks/53204.js:21:82188)\n' +
2024-03-15 21:21:00     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-03-15 21:21:00     '    at async W (/app/projects/app/.next/server/chunks/82729.js:31:1242)\n' +
2024-03-15 21:21:00     '    at async w (/app/projects/app/.next/server/chunks/82729.js:23:399)\n' +
2024-03-15 21:21:00     '    at async Promise.all (index 0)\n' +
2024-03-15 21:21:00     '    at async I (/app/projects/app/.next/server/chunks/5182.js:54:15961)\n' +
2024-03-15 21:21:00     '    at async /app/projects/app/.next/server/pages/api/core/dataset/data/insertData.js:1:3064'
2024-03-15 21:21:00 }
2024-03-15 21:21:00 [INFO] 2024-03-15 13:21:00 [QA Queue] Done 
2024-03-15 21:21:00 [INFO] 2024-03-15 13:21:00 [Vector Queue] Done 
2024-03-15 21:22:00 [INFO] 2024-03-15 13:22:00 [Vector Queue] Done 
2024-03-15 21:22:00 [INFO] 2024-03-15 13:22:00 [QA Queue] Done 
2024-03-15 21:23:00 [INFO] 2024-03-15 13:23:00 [QA Queue] Done 
2024-03-15 21:23:00 [INFO] 2024-03-15 13:23:00 [Vector Queue] Done

**Comment by teeemoom** [comment]
![微信截图_20240315212205](https://github.com/labring/FastGPT/assets/143974082/56062e0e-b8e4-4456-8479-10adea82f0a6)
有人解决了这个问题吗？
