### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'model')

### ISSUE THREAD

**Issue by louisdai** [labring/FastGPT#843]
用docker部署后，在创建知识库的时候，页面崩溃。
控制台有如下错误
framework-4044c6ea3e034f81.js:9 TypeError: Cannot read properties of undefined (reading 'model')
    at t.default (440-5df7ec0198023c59.js:1:4607)
    at ak (framework-4044c6ea3e034f81.js:9:60903)
    at i (framework-4044c6ea3e034f81.js:9:119424)
    at oD (framework-4044c6ea3e034f81.js:9:99077)
    at framework-4044c6ea3e034f81.js:9:98944
    at oO (framework-4044c6ea3e034f81.js:9:98951)
    at oE (framework-4044c6ea3e034f81.js:9:95703)
    at oP (framework-4044c6ea3e034f81.js:9:96092)
    at r5 (framework-4044c6ea3e034f81.js:9:44813)

**Comment by cxl086** [comment]
请问如何解决的？对比了配置文件，没发现什么问题

**Comment by fictionking** [comment]
参见 #875
