### ISSUE TITLE
error: invalid message format

### ISSUE THREAD

**Issue by JBX2060** [labring/FastGPT#86]
没有需要【索引】的数据, 0
error: invalid message format
    at Parser.parseErrorMessage (C:\Users\JBX2060\Desktop\FastGPT\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (C:\Users\JBX2060\Desktop\FastGPT\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\JBX2060\Desktop\FastGPT\node_modules\pg-protocol\dist\parser.js:39:38)
    at TLSSocket.<anonymous> (C:\Users\JBX2060\Desktop\FastGPT\node_modules\pg-protocol\dist\index.js:11:42)
    at TLSSocket.emit (node:events:511:28)
    at addChunk (node:internal/streams/readable:332:12)
    at readableAddChunk (node:internal/streams/readable:305:9)
    at Readable.push (node:internal/streams/readable:242:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 81,
  severity: 'ERROR',
  code: '08P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'pqformat.c',
  line: '640',
  routine: 'pq_getmsgend'
}

**Comment by c121914yu** [comment]
内容包含sql无法存储的字符。得检查一下
