### ISSUE TITLE
重新部署后，无法增加新知识库数据且所有向量检索无效，oneapi向量模型正常无调整

### ISSUE THREAD

**Issue by a491004300** [labring/FastGPT#889]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [ ] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

**问题描述**
fastgpt    | [ERROR] 2024-02-25 10:48:13 response error: Connection terminated due to connection timeout 
fastgpt    | {
fastgpt    |   message: 'Connection terminated due to connection timeout',
fastgpt    |   stack: 'Error: Connection terminated due to connection timeout\n' +
fastgpt    |     '    at /app/projects/app/.next/server/chunks/62172.js:1:10542\n' +
fastgpt    |     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
fastgpt    |     '    at async Y (/app/projects/app/.next/server/chunks/62522.js:20:288)\n' +
fastgpt    |     '    at async Promise.all (index 1)\n' +
fastgpt    |     '    at async o (/app/projects/app/.next/server/pages/api/support/user/team/limit/datasetSizeLimit.js:1:2028)\n' +
fastgpt    |     '    at async /app/projects/app/.next/server/pages/api/core/dataset/data/insertData.js:1:2959'
fastgpt    | }
mongo      | {"t":{"$date":"2024-02-25T10:48:35.175+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"Checkpointer","msg":"WiredTiger message","attr":{"message":"[1708858115:175501][1:0x7f6d07813700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 503, snapshot max: 503 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 456623"}}
mongo      | {"t":{"$date":"2024-02-25T10:48:53.558+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn60","msg":"Connection ended","attr":{"remote":"172.25.0.3:57818","uuid":"6f3ab5cb-e241-4ecb-b09f-7bc29b32a4ca","connectionId":60,"connectionCount":21}}
mongo      | {"t":{"$date":"2024-02-25T10:48:53.558+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.25.0.3:58180","uuid":"1f5ff976-569f-40d1-8833-05611668850f","connectionId":77,"connectionCount":22}}
mongo      | {"t":{"$date":"2024-02-25T10:48:53.559+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn77","msg":"client metadata","attr":{"remote":"172.25.0.3:58180","client":"conn77","doc":{"driver":{"name":"nodejs|Mongoose","version":"5.9.1|7.6.8"},"platform":"Node.js v18.17.1, LE","os":{"name":"linux","architecture":"x64","version":"3.10.0-1062.12.1.el7.x86_64","type":"Linux"}}}}
mongo      | {"t":{"$date":"2024-02-25T10:48:53.560+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn77","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"username","authenticationDatabase":"admin","remote":"172.25.0.3:58180","extraInfo":{}}}
**复现步骤**
增加知识库新数据，或对话时涉及知识库查询
**预期结果**

**相关截图**

**Comment by a491004300** [comment]
![1708859563687](https://github.com/labring/FastGPT/assets/47101077/c877bde7-d20e-4bab-9975-100d6c713b5f)

**Comment by a491004300** [comment]
[ERROR] 2024-02-26 03:41:28 response error: Connection terminated due to connection timeout
{
message: 'Connection terminated due to connection timeout',
stack: 'Error: Connection terminated due to connection timeout\n' +
' at /app/projects/app/.next/server/chunks/62172.js:1:10542\n' +
' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
' at async Y (/app/projects/app/.next/server/chunks/62522.js:20:288)\n' +
' at async Promise.all (index 1)\n' +
' at async a (/app/projects/app/.next/server/pages/api/core/dataset/data/insertData.js:1:2246)\n' +
' at async /app/projects/app/.next/server/pages/api/core/dataset/data/insertData.js:1:2959'
}

我之前doc部署的是正常使用的 重新部署后就出现了这个问题

**Comment by a491004300** [comment]
![image](https://github.com/labring/FastGPT/assets/47101077/e183473a-4488-4ea5-9b02-87c703446c5b)
