### ISSUE TITLE
HTTP 的 GET 请求一直返回 403

### ISSUE THREAD

**Issue by 1wingedangel** [labring/FastGPT#949]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](https://doc.fastgpt.in/docs/intro/)
- [x] 我使用了自己的 key，并确认我的 key 是可正常使用的
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**你的版本**

- [ ] 公有云版本
- [x] 私有部署版本

Docker-Compose 部署，版本 4.6.8。

**问题描述**

我尝试了两种 HTTP 的 GET 请求（Google Custom Search API 和 TMDB的API），在其他软件里可以正常接收到 json 响应，但是在  FastGPT 的高级编排功能中的 HTTP 模块中却返回 403错误 （Request failed with status code 403）。也不知道是哪里有问题。

响应结果以TMDB的API为例：

```
{
  "error": {
    "message": "Request failed with status code 403",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 403
     at settle (file:///app/node_modules/.pnpm/axios@1.6.7/node_modules/axios/lib/core/settle.js:19:12)
     at IncomingMessage.handleStreamEnd (file:///app/node_modules/.pnpm/axios@1.6.7/node_modules/axios/lib/adapters/http.js:589:11)
     at IncomingMessage.emit (node:events:526:35)
     at endReadableNT (node:internal/streams/readable:1359:12)
     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
     at Axios.request (file:///app/node_modules/.pnpm/axios@1.6.7/node_modules/axios/lib/core/Axios.js:45:41)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async i (/app/projects/app/.next/server/chunks/91755.js:255:4374)
     at async Object.d [as httpRequest468] (/app/projects/app/.next/server/chunks/91755.js:255:3798)
     at async j (/app/projects/app/.next/server/chunks/91755.js:254:7083)
     at async Promise.all (index 0)
     at async Promise.all (index 0)
     at async Promise.all (index 0)
     at async Promise.all (index 0)
     at async Q (/app/projects/app/.next/server/chunks/91755.js:254:8057)",
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "adapter": [
        "xhr",
        "http"
      ],
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "Authorization": "Bearer  xxxxx",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
        "Accept-Encoding": "gzip, deflate, br",
        "Content-Length": "2"
      },
      "method": "get",
      "baseURL": "http://xxxx:3000",
      "url": "https://api.themoviedb.org/3/search/movie",
      "params": {
        "query": "怪物",
        "include_adult": "true",
        "language": "zh-CN"
      },
      "data": "{}"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 403
  }
}
```

**复现步骤**

- HTTP 模块中选择使用 GET 请求
- 调试应用

**预期结果**

- 能够正常获取响应。

**相关截图**
![image](https://github.com/labring/FastGPT/assets/396190/60ae2477-ec8d-434f-b751-dd38c444a337)
![image](https://github.com/labring/FastGPT/assets/396190/8f7b34ba-ddf3-4459-adfd-0472613345d3)
![image](https://github.com/labring/FastGPT/assets/396190/efd8add9-1c54-4ea9-84c7-79a251132ab1)

**Comment by c121914yu** [comment]
这不是接口问题么

**Comment by c121914yu** [comment]
![image](https://github.com/labring/FastGPT/assets/50446880/172488c5-e5bc-4686-a61c-aff0d7c4d6d4)

**Comment by erdun** [comment]
https://doc.fastgpt.in/docs/development/openapi/dataset/#%E5%88%9B%E5%BB%BA%E8%AE%AD%E7%BB%83%E8%AE%A2%E5%8D%95469%E5%9C%B0%E5%9D%80%E5%8F%91%E7%94%9F%E6%94%B9%E5%8A%A8

文档中 创建一个知识库  创建成功
其他几个好像都是403
